<?php
if ( empty ($arrFriendList) )
{

    return;
}
?>

<div class="ibox">
    <div class="ibox-content">
        <div id="contact_list">
   
         <input type="text" id="contact-list-search" placeholder="Search Friends" />

            <div class="contact-list-offline offline-status-text" onclick="toggleChatStatus()">Turn off chat</div>

            <ul id="" class="list-group clear-list contact-list-user">
                <?php foreach ($arrFriendList as $objUser) { ?>
                    <li class="list-group-item fist-item hide">
                        <a href="/blab/chat/messenger?username=<?= $objUser->getUsername () ?>">
                            <span class="pull-left">

                                <?php
                                $image = file_exists ($rootPath . '/blab/public/uploads/profile/' . $objUser->getUsername () . '.jpg') ? '/blab/public/uploads/profile/' . $objUser->getUsername () . '.jpg' : '/blab/public/img/avatar.gif';
                                ?>

                                <img class="img-responsive" style="width:20px; margin-right: 12px;" src="<?= $image ?>"> </span>
                                <?= $objUser->getFirstname () . ' ' . $objUser->getLastname () ?>
                        </a>
                        </a>

                    </li>

                <?php } ?>

            </ul>
        </div>
        <br clear="all">
    </div>
</div>