<?php
if ( empty ($arrFriendList) )
{

    return;
}
?>

<div class="ibox">
    <div class="ibox-content">
        <div id="contact_list">
            <ul class="list-group clear-list">
                <?php foreach ($arrFriendList as $objUser) { ?>
                    <li class="list-group-item fist-item">
                        <a href="/blab/chat/messenger?username=<?= $objUser->getUsername () ?>">
                            <span class="pull-left">

                                <?php
                                $image = file_exists ($rootPath . '/blab/public/uploads/profile/' . $objUser->getUsername () . '.jpg') ? '/blab/public/uploads/profile/' . $objUser->getUsername () . '.jpg' : '/blab/public/img/avatar.gif';
                                ?>

                                <img class="img-responsive" style="width:20px; margin-right: 12px;" src="<?= $image ?>"> </span>
                                <?= $objUser->getFirstname () . ' ' . $objUser->getLastname () ?>
                        </a>
                        </a>

                    </li>

                <?php } ?>

            </ul>
        </div>
        <br clear="all">
    </div>
</div>
