<div class="ibox pull-left" style="width: 100%;">
    <div class="ibox-content" style="padding: 0px !important; float: left;width: 100%;">

        <div class="vprofile_o_title" style="padding:0px;">
            <div style="float:left; padding:10px;">
                <i class="fa fa-group v_the_iconed"></i> Groups
            </div>

            <div style="float:right; padding:10px;">

                <span id="view_or_edit_buttonD">
                    <i class="fa fa-plus-square v_the_iconed"></i> <span class="vpb_hover vview_item" onclick="vpb_reset_current_group_details ();"> Create Group</span>

                </span>

            </div><div style="clear:both;"></div>

        </div>


        <ul class="list-group clear-list" style="padding: 10px;">
            <?php
            if ( !empty ($arrGroups) ){
                foreach ($arrGroups as $arrGroup){
                    ?>

                    <li class="col-lg-6" style="list-style: none;">
                        <a href="/blab/group/index/<?= $arrGroup->getId () ?>">
                            <img style="max-width: 50px;" title="<?= $arrGroup->getGroupName () ?>" src="<?= $arrGroup->getImageLocation () ?>" class="img-responsive">
                       
                            <?= $arrGroup->getGroupName () ?>
                        </a>
                    </li>

                    <?php
                }
            } else {
                echo '<h3>You have no groups</h3>';
            }
            ?>

        </ul>
    </div>
</div>