<div class="vprofile_o_title" style="padding:0px;">
    <div style="float:left; padding:10px;">
        <i class="fa fa-group v_the_iconed"></i> Menu
    </div>
    <div style="clear:both;"></div>

</div>

<ul class="list-group clear-list">
    <li class="list-group-item fist-item"><a style="font-size: 16px;" href="/blab/product/index"><img src="/blab/public/img/shopping-cart.png"> Go Shopping</a></li>
    <li class="list-group-item"><a style="font-size: 16px;" href="/blab/index/index"><img src="/blab/public/img/newspaper.png"> News Feed</a></li>
    <li class="list-group-item"><a style="font-size: 16px;" href="/blab/chat/messenger"><img src="/blab/public/img/chat.png"> Go chat</a>
<span class="label label-warning pull-right chat-label">0</span>
</li>
    <li class="list-group-item"><a style="font-size: 16px;" href="/blab/page/createPage"><img src="/blab/public/img/exit.png"> Add New Page</a></li>
    <li class="list-group-item"><a style="font-size: 16px;" href="/blab/index/profile/<?= $_SESSION['user']['username'] ?>"><img src="/blab/public/img/user.png">My profile</a>
    <li onclick="retrieveFriendRequests ()" class="list-group-item"><a style="font-size: 16px;" href="#"><img src="/blab/public/img/friend-request.png">Friend Requests</a>
<span class="label label-warning pull-right request-label">0</span>
</li>
<li onclick="vpb_show_notifications_details('michaelhampton');" class="list-group-item"><a style="font-size: 16px;" href="#"><img src="/blab/public/img/notification.png">Notifications </a>
<span class="label label-warning pull-right notification-label">0</span>
</li>

<li class="list-group-item"><a style="font-size: 16px;" href="/blab/advert/createProfileBanner"><img src="/blab/public/img/photo-slideshow.png">Create Slideshow </a>


</ul>
