<div class="vprofile_o_title" style="padding:0px;">
    <div style="float:left; padding:10px;">
        <i class="fa fa-group v_the_iconed"></i> Menu
    </div>
    <div style="clear:both;"></div>

</div>

<ul class="list-group clear-list">
    <li class="list-group-item fist-item"><a href="/blab/product/index"><i class="fa fa-shopping-cart"></i> Go Shopping</a></li>
    <li class="list-group-item"><a href="/blab/index/index"><i class="fa fa-newspaper-o"></i> News Feed</a></li>
    <li class="list-group-item"><a href="/blab/chat/messenger"><i class="fa fa-envelope-o"></i> Go chat</a></li>
    <li class="list-group-item"><a href="/blab/page/createPage"><i class="fa fa-envelope-o"></i> Add New Page</a></li>
    <li class="list-group-item"><a href="/blab/index/profile/<?= $_SESSION['user']['username'] ?>"><i class="fa fa-newspaper-o"></i> My profile</a>
    <li onclick="retrieveFriendRequests ()" class="list-group-item"><a href="#"><i class="fa fa-user"></i>Friend Requests</a>

</ul>



