<?php if ( !empty ($objPage) ): ?> 

    <div class="ibox">
        <div class="ibox-content">
            <h3><?= $objPage->getName () ?></h3>
            <ul class="list-group clear-list">
                <li class="list-group-item fist-item">
                    <?= $objPage->getAddress () . " " . $objPage->getPostcode () ?>
                </li>
                <li class="list-group-item">
                    <?= $objPage->getTelephoneNo () ?>
                </li>
                <li class="list-group-item">
                    <a href="<?= $objPage->getWebsiteUrl () ?>"><?= $objPage->getWebsiteUrl () ?></a>
                </li>
                <li class="list-group-item">
                    <?= $objPage->getDescription () ?>
                </li>

            </ul>

        </div>
    </div>

<?php endif; ?>