<div class="ibox pull-left" style="width: 100%;">
    <div class="ibox-content" style="padding: 0px !important; float: left;width: 100%;">

        <div class="vprofile_o_title" style="padding:0px;">
            <div style="float:left; padding:10px;">
                <i class="fa fa-group v_the_iconed"></i> Pages
                <br><a href="/blab/page/searchPages">See all</a>
            </div>

            <div style="float:right; padding:10px;">

                <span id="view_or_edit_buttonD"> <a href="/blab/page/createPage">
                    <i class="fa fa-plus-square v_the_iconed"></i> <span class="vpb_hover vview_item"> Create Page</span></a>

                </span>

            </div><div style="clear:both;"></div>

        </div>


        <ul class="list-group clear-list" style="padding: 10px;">
            <?php
            if ( !empty ($arrPages) ):
                foreach ($arrPages as $arrPage):
                 $image = trim($arrPage->getFileLocation ()) !== "" && file_exists ($rootPath  . $arrPage->getFileLocation () ) ? $arrPage->getFileLocation ()  : '/blab/public/img/avatar.gif';
                    ?>
                    <a href="/blab/page/index/<?= $arrPage->getUrl () ?>">
                        <img style="width: 50px;" title="<?= $arrPage->getName () ?>" src="<?= $image ?>">
                    </a>



                    <?php
                endforeach;
            endif;
            ?>

        </ul>
    </div>
</div>