<?php
if ( !isset ($arrUser) || empty ($arrUser) || !isset ($friendIds) )
{
    echo 'No user';
    exit;
}

if ( empty ($requestIds) )
{
    $requestIds = [];
}

$formattedUsername = "profile_" . trim (str_replace (".", "", $arrUser->getUsername ()));
?>

<div class="vpb_profile_name" onmouseover="vpb_get_user_onmouseover_data ('<?= $formattedUsername ?>', '<?= $arrUser->getFirstname () . ' ' . $arrUser->getLastname () ?>', 'United Kingdom', '/blab/uploads/profile/<?= $arrUser->getUsername () ?>.jpg');" onmouseout="vpb_get_user_mouseout_data ('<?= $formattedUsername ?>', '<?= $arrUser->getFirstname () . ' ' . $arrUser->getLastname () ?>', 'United Kingdom', '/blab/uploads/profile/<?= $arrUser->getUsername () ?>.jpg');">
    <span id="p_page_name"><?= $arrUser->getFirstname () . ' ' . $arrUser->getLastname () ?></span></div>

<div style="margin-left:120px; position: absolute; z-index:99;">    <div class="dropdown open v_load_user_detail" onmouseover="vpb_get_user_onmouseover_datas ();" onmouseout="vpb_get_user_mouseout_datas ();" id="vpb_load_user_<?= $formattedUsername ?>" style="text-align: left !important; margin: 0px !important; padding: 0px !important; display: none;"> 

        <ul class="dropdown-menu bullet" style="border-radius:0px !important; display:block; margin:15px; z-index:9999;text-align:left !important;margin-top:10px;">

            <div class="dropdown-header" style="padding:10px !important;text-align:left !important; border:0px solid !important;margin:0px !important;">
                <div class="input-group vpb-wall-load-user-detail-wrap">
                    <span class="input-group-addon vpb-wall-load-user-detail-photo" style="cursor:pointer;" onclick="window.location.href = 'http://www.vasplus.info/wall/<?= $arrUser->getUsername () ?>';">
                        <span id="vpb_load_user_photo_">

                            <?php
                            if ( file_exists ($rootPath . '/blab/public/uploads/profile/' . $arrUser->getUsername () . '.jpg') )
                            {
                                echo '<img src="/blab/public/uploads/profile/' . $arrUser->getUsername () . '.jpg"  class="icon-choose-image"/>';
                            }
                            else
                            {
                                echo '<img src="/blab/public/img/avatar.gif"  class="icon-choose-image"/>';
                            }
                            ?>

                        </span>
                    </span>
                    <div class="vpb-wall-load-user-detail-others">
                        <span class="vpb-wall-load-user-detail-fullname" onclick="window.location.href = '/blab/index/profile/<?= $arrUser->getUsername () ?>';"><span id="vpb_load_user_fullname_<?= $formattedUsername ?>">Lexi Hampton</span></span><br>
                        <span style="font-weight:normal !important;" id="vpb_load_user_country_<?= $formattedUsername ?>"><i class="fa fa-map-marker" title="Location"></i>&nbsp;United Kingdom</span>

                        <input type="hidden" id="vpb_friendship_uid_<?= $formattedUsername ?>" value="<?= $arrUser->getUsername () ?>">
                        <input type="hidden" id="vpb_friendship_fid_<?= $formattedUsername ?>" value="<?= $arrUser->getUsername () ?>">
                    </div>
                </div>
            </div>
            <div style="clear:both;"></div>
            <div class="modal-footer" style="padding:10px !important; background-color:#F6F6F6; margin:0px;">
                <span id="vpb_load_friendship_<?= $formattedUsername ?>"><span id="addfriend_6536" onclick="vpb_friend_ship ('<?= $arrUser->getId () ?>', '<?= $arrUser->getUsername () ?>', 'addfriend');" class="cbt_friendship"><i class="fa fa-user-plus"></i> Add Friend</span>

                    <span style="opacity:0.6;cursor:default;display:none;" id="requestsent_6536" class="cbt_friendship"><i class="fa fa-reply"></i> Request Sent</span>

                    <span style="display:none;" title="Cancel Request" id="cancelrequest_6536" onclick="vpb_friend_ship ('<?= $arrUser->getId () ?>', '<?= $arrUser->getUsername () ?>', 'cancelrequest');" class="cbt_friendship vpb_cbtn"><i class="fa fa-times"></i></span></span>

                <span style="margin-left:16px !important;" class="cbt_friendship" onclick="window.location.href = '/blab/index/profile/<?= $arrUser->getUsername () ?>';"><i class="fa fa-user"></i> Profile</span>
            </div>
        </ul>
    </div>
</div>

<?php
if ( file_exists ($rootPath . '/blab/public/uploads/profile/' . $arrUser->getUsername () . '.jpg') )
{
    $bacgroundImage = '/blab/public/uploads/profile/' . $arrUser->getUsername () . '.jpg';
}
else
{
    $bacgroundImage = '/blab/public/img/avatar.gif';
}
?>
<div id="updateProfilePic">
    <div class="profilephoto_wrap">
        <div class="vprofilephoto" style="background-image: url('<?= $bacgroundImage ?>');">
        </div>

        <?php
        if ( $arrUser->getId () == $_SESSION['user']['user_id'] )
        {
            echo '<div class="vprofilephoto_editer" data-backdrop="static" data-toggle="modal" data-target="#add-profile-photo"><i class="fa fa-camera"></i> Update Photo</div>';
        }
        else
        {
            $userId = (int) $arrUser->getId ();

            $showRequest = !in_array ($userId, $friendIds) && !in_array ($userId, $requestIds) ? 'inline-block' : 'none';
            $showRemove = in_array ($userId, $friendIds) ? 'inline-block' : 'none !important';
            $showBlock = !in_array ($userId, $arrUnblockedList) ? 'inline-block' : 'none';
            $showUnblock = in_array ($userId, $arrUnblockedList) ? 'inline-block' : 'none';
            $showCancel = in_array ($userId, $requestIds) ? 'inline-block' : 'none';
            ?>
            <div style="margin:0 auto; width:100%; padding-top:10px; padding-bottom:10px; background-color:#F9F9F9; text-align:center !important;border: 5px solid #F1F1F1; border-top:0px solid;box-shadow: 0 1px 1px rgba(0, 0, 0, 0.1); font-size:18px !important; display:block; color:#000;"><span id="vpb_show_friendship_button"><span id="unfriend_<?= $arrUser->getId () ?>" onclick="vpb_friend_ship ('<?= $arrUser->getId () ?>', '<?= $formattedUsername ?>', 'unfriend');" class="cbt_friendship" style="display: none;"><i class="fa fa-times"></i> Unfriend</span>

                    <span style="display:<?= $showRemove ?>" id="unfriend_<?= $arrUser->getId () ?>" onclick="vpb_friend_ship ('<?= $arrUser->getId () ?>', 'victor', 'unfriend');" class="cbt_friendship"><i class="fa fa-times"></i> Unfriend</span> 
                    <span style="display:<?= $showBlock ?>" id="block_<?= $arrUser->getId () ?>" onclick="block_user ('<?= $arrUser->getId () ?>', 'block');" class="cbt_friendship"><i class="fa fa-times"></i> Block</span> 

                    <span style="display: <?= $showUnblock ?>" id="unblock_<?= $arrUser->getId () ?>" onclick="block_user ('<?= $arrUser->getId () ?>', 'unblock');" class="cbt_friendship"><i class="fa fa-user-plus"></i> Unblock</span>

                    <span style="display: <?= $showRequest ?>" id="addfriend_<?= $arrUser->getId () ?>" onclick="vpb_friend_ship ('<?= $arrUser->getId () ?>', '<?= $formattedUsername ?>', 'addfriend');" class="cbt_friendship"><i class="fa fa-user-plus"></i> Add Friend</span>

                    <span style="opacity: 0.6; cursor: default; display: none;" id="requestsent_<?= $arrUser->getId () ?>" class="cbt_friendship"><i class="fa fa-reply"></i> Request Sent</span>

                    <span style="display: <?= $showCancel ?>" title="Cancel Request" id="cancelrequest_<?= $arrUser->getId () ?>" onclick="vpb_friend_ship ('<?= $arrUser->getId () ?>', '<?= $formattedUsername ?>', 'cancelrequest');" class="cbt_friendship vpb_cbtn"><i class="fa fa-times"></i>Cancel Request</span>

                </span></div>
            <?php
        }
        ?>


    </div> 




    <br clear="all"><br clear="all"><br clear="all">        </div>