<div class="vmiddle_other" style="border-bottom:0PX solid !important; display: none;" id="vasplus_wall_find_friends">

    <a href="#" style="font-size:26px;" class="pull-left" onclick="vpb_show_find_new_friends_box ('suggest')"><i class="fa fa-search">Suggest Friends</i></a>
    <a href="#" style="font-size:26px;" class="pull-left" onclick="vpb_show_find_new_friends_box ()"><i class="fa fa-users"></i>Friends</a>

    <input type="hidden" id="vtotal_friends" value="<?= count ($arrFriendList) ?>">
    <input type="hidden" id="vpb_friends_start" value="1">

    <div class="vmiddle_other_title vprofile_o_title" style="border-bottom:0px solid;">
        <div style="float:left;">Find Friend <?= count ($arrFriendList) ?></div>
        <div style="float:right; font-weight:normal !important; font-size:13px !important;">
            <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" onclick="vpb_show_status_updates ();" data-toggle="tooltip" data-placement="top" title="" data-original-title="Close">×</button>
        </div>
        <div style="clear:both;"></div>
    </div>

    <div class="input-group vpb-the-friends-wrap" id="vpb_load_more_friends_box">
        <div style="float:left;"><span class="vpb_hover" style="color:#3b5998;" onclick="vpb_load_more_page_owner_friends (<?= $objUser->getId () ?>);">View more friends</span></div>
        <div style="float:right; color:#999;"><span id="v_this_friends_totals"><?= count ($arrFilteredFriendList) ?></span> of <?= count ($arrFriendList) ?></div>
        <div style="clear:both;"></div>
    </div>

    <div class="input-group">
        <input type="text" class="form-control form-control-plus-plus" name="vfrnds_data" id="vfrnds_data" value="" placeholder="Search..." autocomplete="off" style=" border-left:0px solid !important;" onkeyup="vpb_search_friends ();" onkeydown="vpb_search_friends ();">
        <span class="input-group-addon input-group-addon-plus" onclick="vpb_search_friends ();" style="border-radius:0px !important; border-right:0px solid;"><i class="fa fa-search"></i></span>

    </div>   

    <div style="padding:10px;" id="vpb_display_wall_find_friends"></div>

    <div style="padding:10px;" id="vpb_get_all_the_users_friends">
        <?php
        if ( !empty ($arrFilteredFriendList) )
        {
            foreach ($arrFilteredFriendList as $key => $arrFriend) {
                ?>
                <div class="vfriendsPhotos_wraper">
                    <span style="display:block; color:#000 !important; margin-bottom: 102px !important;" id="unfriend_<?= $arrFriend->getId () ?>" onclick="vpb_friend_ship ('<?= $arrFriend->getId () ?>', 'victor', 'unfriend');" class="cbt_friendship"><i class="fa fa-times"></i> Unfriend</span> 
                    <span style="display: none; color:#000 !important; margin-bottom:102px;" id="addfriend_<?= $arrFriend->getId () ?>" onclick="vpb_friend_ship ('<?= $arrFriend->getId () ?>', '<?= $arrFriend->getUsername () ?>', 'addfriend');" class="cbt_friendship"><i class="fa fa-user-plus"></i> Add Friend</span>

                    <span style="opacity: 0.6; cursor: default; display: none;color:#000 !important; margin-bottom:102px; " id="requestsent_<?= $arrFriend->getId () ?>" class="cbt_friendship"><i class="fa fa-reply"></i> Request Sent</span>

                    <span style="display: none;color:#000 !important; margin-bottom:102px; " title="Cancel Request" id="cancelrequest_<?= $arrFriend->getId () ?>" onclick="vpb_friend_ship ('<?= $arrFriend->getId () ?>', '<?= $arrFriend->getUsername () ?>', 'cancelrequest');" class="cbt_friendship vpb_cbtn"><i class="fa fa-times"></i>Cancel Request</span>


                    <a href="/blab/index/profile/<?= $arrFriend->getUsername () ?>">

                        <?php
                        if ( file_exists ($rootPath . '/blab/public/uploads/profile/' . $arrFriend->getUsername () . '.jpg') )
                        {
                            echo '<img title="' . $arrFriend->getFirstName () . ' ' . $arrFriend->getLastName () . '" src="/blab/public/uploads/profile/' . $arrFriend->getUsername () . '.jpg">';
                        }
                        else
                        {
                            echo '<img src="/blab/public/img/avatar.gif">';
                        }
                        ?>

                        <span><?= $arrFriend->getFirstname () . ' ' . $arrFriend->getLastname () ?></span>
                    </a> 
                </div>

                <?php
            }
        }
        ?>
    </div>
</div>