<div id="page-wrapper" class="gray-bg" style="min-height: 422px;">
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Terms and Policies</h2>

        </div>
        <div class="col-lg-2">

        </div>
    </div>

    <div class="row" style="margin-top: 16px;">
        <div class="col-lg-12" style="padding:0px;">
            <div class="ibox">
               
                <div class="ibox-content">

                    <div class="row">

                        <div class="col-lg-4">
                            <div class="panel panel-primary">
                                <div class="panel-heading">
                                    Terms and Conditions
                                </div>
                                <div class="panel-body">
                                    <p><a href="/blab/terms/terms">View Our terms and conditions</a></p>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="panel panel-success">
                                <div class="panel-heading">
                                    Privacy Statement / Cookies
                                </div>
                                <div class="panel-body">
                                    <p><a href="/blab/terms/privacy">View our privacy statement.</a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

