<html>
    <head>
        <title></title>
    </head>


    <body bgcolor="#FFFFFF">
    <html>
        <head>
            <title></title>
        </head>


        <body bgcolor="#FFFFFF">
            <h1>Privacy policy</h1>

            <p>
                Here at the blab Philippines we take your privacy seriously and will only use your personal information to administer your account and to provide the products and services you have requested from us.
            </p>
            
            <h2>1.​Introduction</h2>

            <p>
                1.1​ We are committed to safeguarding the privacy of our website visitors. <br>

                1.2​ This policy applies where we are acting as a data controller with respect to the personal data of our website visitors; in other words, where we determine the purposes and means of the processing of that personal data. <br>
                <br>
                1.3​ We use cookies on our website. Insofar as those cookies are not strictly necessary for the provision of [ur website, we will ask you to consent to our use of cookies when you first visit our website.
                <br>
                1.4​ Our website incorporates privacy controls which affect how we will process your personal data. By using the privacy controls, you can specify whether you would like to limit the publication of your information. You can access the privacy controls via http://blab.x10host.com.
                <br>
                1.5​ In this policy, "we", "us" and "our" refer to The Blab. For more information about us, see Section 13.
            </p>


            <h2>2.​Credit</h2>

            <p>
                2.1​ This document was created using a template from SEQ Legal (https://seqlegal.com).
                <br>
                3.​How we use your personal data
                <br><br>
                3.1​ In this Section 3 we have set out:
                <br>
                (a)​the general categories of personal data that we may process;
                <br>
                (b)​in the case of personal data that we did not obtain directly from you, the source and specific categories of that data
                <br>
                (c)​the purposes for which we may process personal data; and
                <br>
                (d)​the legal bases of the processing.
                <br><br>
                3.2​ We may process data about your use of our website and services ("usage data"). The usage data may include your IP address, geographical location, browser type and version, operating system, referral source, length of visit, page views and website navigation paths, as well as information about the timing, frequency and pattern of your service use. The source of the usage data is the only our analytics tracking system. This usage data may be processed for the purposes of analysing the use of the website. The legal basis for this processing is our legitimate interests, namely monitoring and improving our website and services.
                <br><br>
                3.3​ We may process your account data ("account data").
                The account data may include your name and email address.
                The source of the account data is you. The account data may be processed for the purposes of operating our website, providing our services, ensuring the security of our website and services, maintaining back-ups of our databases and communicating with you. The legal basis for this processing is our legitimate interests, namely the proper administration of our website.
                <br><br>
                3.4​ We may process your information included in your personal profile on our website("profile data").
                The profile data may include your name, address, telephone number, email address, profile pictures, gender, date of birth, relationship status, interests and hobbies, educational details and employment details.
                The profile data may be processed for the purposes of enabling and monitoring your use of our website. The legal basis for this processing is our legitimate interests, namely the proper administration of our website.
                <br><br>
                3.6​ We may process information that you post for publication on our website or through our services ("publication data"). 
                The publication data may be processed for the purposes of enabling such publication and administering our website and services. The legal basis for this processing is our legitimate interests, namely the proper administration of our website and business.
                <br><br>
                3.7​ We may process information contained in any enquiry you submit to us regarding goods and/or services ("enquiry data"). The enquiry data may be processed for the purposes of offering, marketing and selling relevant goods and/or services to you.
                <br><br>
                3.8​ We may process information relating to our customer relationships, including customer contact information ("customer relationship data").
                The customer relationship data may include your name, your employer, your job title or role, your contact details, and information contained in communications between us and you.The source of the customer relationship data is you.
                The customer relationship data may be processed for the purposes of managing our relationships with customers, communicating with customers, keeping records of those communications and promoting our products and services to customers]. The legal basis for this processing is our legitimate interests, namely the proper management of our customer relationships.
                <br><br>
                3.9​ We may process [information relating to transactions, including purchases of goods and services, that you enter into with us and/or through our website] ("transaction data").[ The transaction data may include [your contact details, your card details and the transaction details].] The transaction data may be processed [for the purpose of supplying the purchased goods and services and keeping proper records of those transactions]. The legal basis for this processing is [the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract and our legitimate interests, namely [the proper administration of our website and business]] OR [[specify basis]].
                <br><br>
                3.10​ We may process information that you provide to us for the purpose of subscribing to our email notifications ("notification data"). The notification data may be processed for the purposes of sending you the relevant notifications. The legal basis for this processing is the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract.
                <br><br>
                3.11​ We may process information contained in or relating to any communication that you send to us ("correspondence data"). The correspondence data may include the communication content and metadata associated with the communication. Our website will generate the metadata associated with communications made using the website contact forms. The correspondence data may be processed for the purposes of communicating with you and record-keeping. The legal basis for this processing is our legitimate interests, namely the proper administration of our website and business and communications with users.
                <br><br>
                3.12​ We may process [identify general category of data].[ This data may include [list specific items of data].][ The source of this data is [identify source].] This data may be processed for [specify purposes]. The legal basis for this processing is [consent] OR [our legitimate interests, namely [specify legitimate interests]] OR [the performance of a contract between you and us and/or taking steps, at your request, to enter into such a contract] OR [[specify basis]].
                <br><br>
                3.13​ We may process any of your personal data identified in this policy where necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure. The legal basis for this processing is our legitimate interests, namely the protection and assertion of our legal rights, your legal rights and the legal rights of others.
                <br><br>
                3.14​ We may process any of your personal data identified in this policy where necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, or obtaining professional advice. The legal basis for this processing is our legitimate interests, namely the proper protection of our business against risks.
                <br><br>
                3.15​ In addition to the specific purposes for which we may process your personal data set out in this Section 3, we may also process any of your personal data where such processing is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.
                <br><br>
                3.16​ Please do not supply any other person's personal data to us, unless we prompt you to do so.
            </p>

            <h2>4.​Providing your personal data to others</h2>
            <p>
                4.1​ We may disclose your personal data] to any member of our group of companies (this means our subsidiaries, our ultimate holding company and all its subsidiaries) insofar as reasonably necessary for the purposes, and on the legal bases, set out in this policy.[ Information about our group of companies can be found at [URL].]
                <br><br>
                4.2​We may disclose your personal data to [our insurers and/or professional advisers insofar as reasonably necessary for the purposes of obtaining or maintaining insurance coverage, managing risks, obtaining professional advice, or the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure].
                <br><br>
                4.3 Financial transactions relating to our website may be handled by our payment services providers, PayPal . We will share transaction data with our payment services providers only to the extent necessary for the purposes of processing your payments, refunding such payments and dealing with complaints and queries relating to such payments and refunds.
                <br><br>
                4.4 We may disclose [your enquiry data] to [one or more of those selected third party suppliers of goods and services identified on our website] for the purpose of [enabling them to contact you so that they can offer, market and sell to you relevant goods and/or services].[ Each such third party will act as a data controller in relation to the enquiry data that we supply to it; and upon contacting you, each such third party will supply to you a copy of its own privacy policy, which will govern that third party's use of your personal data.]
                <br><br>
                4.5 In addition to the specific disclosures of personal data set out in this Section 4, we may disclose your personal data where such disclosure is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person. We may also disclose your personal data where such disclosure is necessary for the establishment, exercise or defence of legal claims, whether in court proceedings or in an administrative or out-of-court procedure.

            </p>

            <h2>5.​International transfers of your personal data</h2>

            <p>
                5.1​ In this Section 5, we provide information about the circumstances in which your personal data may be transferred to countries outside the European Economic Area (EEA).
                <br><br>
                5.2 The hosting facilities for our website are situated in USA. The European Commission has made an "adequacy decision" with respect to the data protection laws of each of these countries.] Transfers to each of these countries will be protected by appropriate safeguards, namely the use of standard data protection clauses adopted or approved by the European Commission, a copy of which you can find at our website 

                <br><br>
                5.3 You acknowledge that personal data that you submit for publication through our website may be available, via the internet, around the world. We cannot prevent the use (or misuse) of such personal data by others.

            </p>

            <h2>6.​Retaining and deleting personal data</h2>

            <p>
                6.1​ This Section 6 sets out our data retention policies and procedure, which are designed to help ensure that we comply with our legal obligations in relation to the retention and deletion of personal data.
                <br><br>
                6.2​Personal data that we process for any purpose or purposes shall not be kept for longer than is necessary for that purpose or those purposes.
                <br><br>
                6.3​We will retain your personal data as follows:
                <br>
                (a)​ personal data will be retained for the lifetime of your account .
                <br><br>
                6.5​Notwithstanding the other provisions of this Section 6, we may retain your personal data where such retention is necessary for compliance with a legal obligation to which we are subject, or in order to protect your vital interests or the vital interests of another natural person.

            </p>


            <h2>7.​Amendments</h2>

            <p>
                7.1​We may update this policy from time to time by publishing a new version on our website.
                <br><br>
                7.2​You should check this page occasionally to ensure you are happy with any changes to this policy.
                <br><br>
                7.3​ We may notify you of significant changes to this policy by email or through the private messaging system on our website.
            </p>


            <h2> 8.​Your rights</h2>

            <p> 8.1​In this Section 8, we have summarised the rights that you have under data protection law. Some of the rights are complex, and not all of the details have been included in our summaries. Accordingly, you should read the relevant laws and guidance from the regulatory authorities for a full explanation of these rights.
                <br><br>
                8.2​Your principal rights under data protection law are:
                <br>
                (a)​the right to access;
                <br>
                (b)​the right to rectification;
                <br>
                (c)​the right to erasure;
                <br>
                (d)​the right to restrict processing;
                <br>
                (e)​the right to object to processing;
                <br>
                (f)​the right to data portability;
                <br>
                (g)​the right to complain to a supervisory authority; and
                <br>
                (h)​the right to withdraw consent.
                <br>
                8.3​You have the right to confirmation as to whether or not we process your personal data and, where we do, access to the personal data, together with certain additional information. That additional information includes details of the purposes of the processing, the categories of personal data concerned and the recipients of the personal data. Providing the rights and freedoms of others are not affected, we will supply to you a copy of your personal data. The first copy will be provided free of charge, but additional copies may be subject to a reasonable fee. You can access your personal data by visiting [URL] when logged into our website.
                <br><br>
                8.4​You have the right to have any inaccurate personal data about you rectified and, taking into account the purposes of the processing, to have any incomplete personal data about you completed.
                <br><br>
                8.5​In some circumstances you have the right to the erasure of your personal data without undue delay. Those circumstances include: the personal data are no longer necessary in relation to the purposes for which they were collected or otherwise processed; you withdraw consent to consent-based processing; you object to the processing under certain rules of applicable data protection law; the processing is for direct marketing purposes; and the personal data have been unlawfully processed. However, there are exclusions of the right to erasure. The general exclusions include where processing is necessary: for exercising the right of freedom of expression and information; for compliance with a legal obligation; or for the establishment, exercise or defence of legal claims.
                <br><br>
                8.6​In some circumstances you have the right to restrict the processing of your personal data. Those circumstances are: you contest the accuracy of the personal data; processing is unlawful but you oppose erasure; we no longer need the personal data for the purposes of our processing, but you require personal data for the establishment, exercise or defence of legal claims; and you have objected to processing, pending the verification of that objection. Where processing has been restricted on this basis, we may continue to store your personal data. However, we will only otherwise process it: with your consent; for the establishment, exercise or defence of legal claims; for the protection of the rights of another natural or legal person; or for reasons of important public interest.
                <br><br>
                8.7​You have the right to object to our processing of your personal data on grounds relating to your particular situation, but only to the extent that the legal basis for the processing is that the processing is necessary for: the performance of a task carried out in the public interest or in the exercise of any official authority vested in us; or the purposes of the legitimate interests pursued by us or by a third party. If you make such an objection, we will cease to process the personal information unless we can demonstrate compelling legitimate grounds for the processing which override your interests, rights and freedoms, or the processing is for the establishment, exercise or defence of legal claims.
                <br><br>
                8.8​You have the right to object to our processing of your personal data for direct marketing purposes (including profiling for direct marketing purposes). If you make such an objection, we will cease to process your personal data for this purpose.
                <br><br>
                8.9​You have the right to object to our processing of your personal data for scientific or historical research purposes or statistical purposes on grounds relating to your particular situation, unless the processing is necessary for the performance of a task carried out for reasons of public interest.
                <br><br>
                8.10​To the extent that the legal basis for our processing of your personal data is:
                <br>
                (a)​consent; or <br>

                (b)​that the processing is necessary for the performance of a contract to which you are party or in order to take steps at your request prior to entering into a contract,
                <br>
                ​and such processing is carried out by automated means, you have the right to receive your personal data from us in a structured, commonly used and machine-readable format. However, this right does not apply where it would adversely affect the rights and freedoms of others.
                <br><br>
                8.11​If you consider that our processing of your personal information infringes data protection laws, you have a legal right to lodge a complaint with a supervisory authority responsible for data protection. You may do so in the EU member state of your habitual residence, your place of work or the place of the alleged infringement.
                <br><br>
                8.12​To the extent that the legal basis for our processing of your personal information is consent, you have the right to withdraw that consent at any time. Withdrawal will not affect the lawfulness of processing before the withdrawal.
                <br><br>
                8.13​You may exercise any of your rights in relation to your personal data by written notice to us, in addition to the other methods specified in this Section 8.
            </p>


            <h2>9.​About cookies</h2>

            <p>
                9.1​A cookie is a file containing an identifier (a string of letters and numbers) that is sent by a web server to a web browser and is stored by the browser. The identifier is then sent back to the server each time the browser requests a page from the server.
                <br><br>
                9.2​Cookies may be either "persistent" cookies or "session" cookies: a persistent cookie will be stored by a web browser and will remain valid until its set expiry date, unless deleted by the user before the expiry date; a session cookie, on the other hand, will expire at the end of the user session, when the web browser is closed.
                <br><br>
                9.3​Cookies do not typically contain any information that personally identifies a user, but personal information that we store about you may be linked to the information stored in and obtained from cookies.

            </p>

            <h2>10.​Cookies that we use</h2>

            <p>
                10.1​We use cookies for the following purposes:
                <br>
                (a)​authentication - we use cookies [to identify you when you visit our website and as you navigate our website (cookies used for this purpose are remembering your username and password ;
                <br>
                (b)​status - we use cookies to help us to determine if you are logged into our website;
                <br>
                (c)​[personalisation - we use cookies to store information about your preferences and to personalise the website for you.
                <br>
                (d)​security - we use cookies as an element of the security measures used to protect user accounts, including preventing fraudulent use of login credentials, and to protect our website generally
                <br>
                (e)​advertising - we use cookies [to help us to display advertisements that will be relevant to you

            </p>

            <h2>11.​Cookies used by our service providers</h2>

            <p>
                11.1​Our service providers use cookies and those cookies may be stored on your computer when you visit our website.
                <br><br>
                11.2​We use Google Analytics to analyse the use of our website. Google Analytics gathers information about website use by means of cookies. The information gathered relating to our website is used to create reports about the use of our website. Google's privacy policy is available at: https://www.google.com/policies/privacy/.

            </p>


            <h2>12.​Managing cookies</h2>

            <p> 12.1​Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links:
                <br>
                (a)​https://support.google.com/chrome/answer/95647?hl=en (Chrome);
                <br>
                (b)​https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences (Firefox);
                <br>
                (c)​http://www.opera.com/help/tutorials/security/cookies/ (Opera);
                <br>
                (d)​https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies (Internet Explorer);
                <br>
                (e)​https://support.apple.com/kb/PH21411 (Safari); and
                <br>
                (f)​https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy (Edge).
                <br>
                12.2​Blocking all cookies will have a negative impact upon the usability of many websites.
                <br><br>
                12.3​If you block cookies, you will not be able to use all the features on our website.
            </p>





            <h2>13.​Our details</h2> 

            <p>
                13.1​This website is maintained by Michael Hampton.
                <br><br>
                13.4​ You can contact us by email, using this email address mike@blab.x10host.com
            </p>

        </body>


    </html>

</body>


</html>