
<!--<script src="/blab/public/js/jquery.mentions.js"></script>
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">-->
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="/blab/public/js/bootstrap.js"></script>
<script src="/blab/public/js/slimscroll.js"></script>
<script src="/blab/public/js/pagination.js"></script>
<script src="/blab/public/js/sweetalert.js"></script>
<script src="/blab/public/js/datetime.js"></script>
<script src="/blab/public/js/clockpicker.js"></script>
<!--<script src="/blab/public/js/icheck.js."></script>-->