<head>
    <meta charset="UTF-8">
    <meta name="description" content="A Filipino social network ">
    <meta name="keywords" content="Filipino, Philippines, social, social network, social media">
    <meta name="author" content="Michael hampton ">
    <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'>
    <title><?php echo Phalcon\Tag::getTitle (false); ?></title>

    <script>
        var username = '<?= !empty ($_SESSION['user']['username']) ? $_SESSION['user']['username'] : '' ?>';
    </script>


</head>



<script src="/blab/public/js/jquery-2.1.1.js"></script>
<link href="/blab/public/css/bootstrap.css" rel="stylesheet">
<link href="/blab/public/css/style.css" rel="stylesheet">
<link href="/blab/public/css/animate.css" rel="stylesheet">
<link href="/blab/public/css/newsFeed.css?v=3" rel="stylesheet">
<link href="/blab/public/css/chat.css" rel="stylesheet">
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet" href="/blab/public/css/jquery.mentions.css">
<link href="/blab/public/css/sweetalert.css" rel="stylesheet">
<link href="/blab/public/css/datetime.css" rel="stylesheet">
<link href="/blab/public/css/fonts.css" rel="stylesheet">
<link href="/blab/public/css/clockpicker.css" rel="stylesheet">
<link href="/blab/public/css/select2.css" rel="stylesheet">
<link href="/blab/public/css/select2a.css" rel="stylesheet">
<link href="/blab/public/css/icheck.css" rel="stylesheet">

<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link href="/blab/public/font-awesome/css/font-awesome.css" rel="stylesheet">
<script src="/blab/public/js/convertVideo.js"></script>
<script src="/blab/public/js/search.js"></script>
<script src="/blab/public/js/jquery.mentions.js"></script>
<script src="/blab/public/js/select2.js"></script>

<script src="/blab/public/js/autosize.js"></script>
<script src="/blab/public/js/easing.js"></script>