<link href="/blab/public/css/inbox.css" rel="stylesheet" type="text/css" media="all" />



<script type="text/javascript" src="/blab/public/js/inbox.js?15755"></script>
    <script src="/blab/public/js/geocomplete.js"></script>
    <script src="/blab/public/js/newsFeed.js"></script>
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA1COtE7cJxfGxNWiTjEgtSNhbvDBCiiqQ&libraries=places"></script>
    <script src="/blab/public/js/geocomplete.js"></script>

    <script src="/blab/public/js/profile.js" type="text/javascript"></script>
    <script src="/blab/public/js/chatModal.js" type="text/javascript"></script>

<input type="hidden" id="pageId" name="pageId" value="<?= $pageId ?>">

<!-- This is the function to load messaging system on to this page-->
<script> $ (function ()
    {
        load_messaging_system ();
    });</script> 
<div id="load_messaging_system"></div> 
