<link href="/blab/public/css/inbox.css" rel="stylesheet" type="text/css" media="all" />



<script type="text/javascript" src="/blab/public/js/inbox.js?15755"></script>

<input type="hidden" id="pageId" name="pageId" value="<?= $pageId ?>">

<!-- This is the function to load messaging system on to this page-->
<script> $ (function ()
    {
        load_messaging_system ();
    });</script> 
<div id="load_messaging_system"></div> 
