<?php



$html = buildHtml ($yourDataArray, $total);

echo $html;

if ( $page < $totalPages )
{
    echo ' <div class="loadmore" data-page="' . $nextPage . '">
                        <div class="content"></div>
                        <div class="loading-bar">Scroll for more or click here</div>
                        </div>

                </div>';
}

function blab_time_ago ($timestamp)
{
    $time_ago = strtotime ($timestamp);
    $current_time = time ();
    $time_difference = $current_time - $time_ago;
    $seconds = $time_difference;
    $minutes = round ($seconds / 60);           // value 60 is seconds  
    $hours = round ($seconds / 3600);           //value 3600 is 60 minutes * 60 sec  
    $days = round ($seconds / 86400);          //86400 = 24 * 60 * 60;  
    $weeks = round ($seconds / 604800);          // 7*24*60*60;  
    $months = round ($seconds / 2629440);     //((365+365+365+365+366)/5/12)*24*60*60  
    $years = round ($seconds / 31553280);     //(365+365+365+365+366)/5 * 24 * 60 * 60  
    if ( $seconds <= 60 )
    {
        return "Just Now";
    }
    else if ( $minutes <= 60 )
    {
        if ( $minutes == 1 )
        {
            return "one minute ago";
        }
        else
        {
            return "$minutes minutes ago";
        }
    }
    else if ( $hours <= 24 )
    {
        if ( $hours == 1 )
        {
            return "an hour ago";
        }
        else
        {
            return "$hours hrs ago";
        }
    }
    else if ( $days <= 7 )
    {
        if ( $days == 1 )
        {
            return "yesterday";
        }
        else
        {
            return "$days days ago";
        }
    }
    else if ( $weeks <= 4.3 ) //4.3 == 52/12  
    {
        if ( $weeks == 1 )
        {
            return "a week ago";
        }
        else
        {
            return "$weeks weeks ago";
        }
    }
    else if ( $months <= 12 )
    {
        if ( $months == 1 )
        {
            return "a month ago";
        }
        else
        {
            return "$months months ago";
        }
    }
    else
    {
        if ( $years == 1 )
        {
            return "one year ago";
        }
        else
        {
            return "$years years ago";
        }
    }
}

function buildHtml ($arrComments, $total)
{
    $html = "";

    $totalCommentsToDisplay = 1;
    $postCount = 0;

    foreach ($arrComments as $arrComment) {

        $usersLikes = [];
        $likeCount = 0;
        $likeClass = 'like';
        $likes = '';

        $arrLikes = $arrComment->getArrLikes ();

        if ( !empty ($arrLikes) )
        {
            $usersLikes = array_reduce ($arrLikes, function ($reduced, $current) {

                $fullName = $current->getFirstName () . ' ' . $current->getLastName ();

                $reduced[$current->getUsername ()] = $fullName;
                return $reduced;
            });

            $likes = implode (',', array_slice ($usersLikes, 0, 2));
            $likeCount = count ($usersLikes) - 2;
            $likeClass = !empty ($usersLikes) && array_key_exists ($_SESSION['user']['username'], $usersLikes) ? 'unlike' : $likeClass;
        }

        echo '<div class="social-feed-box">

                                <div class="pull-right social-action dropdown">
                                    <button data-toggle="dropdown" class="dropdown-toggle btn-white">
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu m-t-xs">
                                        <li><a href="#">Config</a></li>
                                    </ul>
                                </div>
                        
                                <div class="social-avatar">
                                    <a href="profile.php?user='.$arrComment->getUserId ().'" class="pull-left">
                                        <img alt="image" src="uploads/profile/' . $arrComment->getUsername () . '.jpg">
                                    </a>
                                    <div class="media-body">
                                        <a href="profile.php?user='.$arrComment->getUserId ().'">
                                            ' . $arrComment->getAuthor () . '
                                        </a>
                                        <small date="' . $arrComment->getCreated () . '" class="text-muted timeAgo">' . blab_time_ago ($arrComment->getCreated ()) . '</small>
                                    </div>
                                </div>
                            
                                <div class="social-body">
                                  <p>
                                     ' . $arrComment->getMessage () . '
                                  </p>';

        $arrImages = $arrComment->getArrImages ();

        if ( !empty ($arrImages) )
        {
            echo '<section id="photos">';

            foreach ($arrImages as $arrImage) {


                echo '<img style="width:100%;" src="' . $arrImage->getFileLocation () . '" class="img-responsive">';
            }

            echo '</section>';
        }

//                            if ( !empty ($arrComment['img']) )
//                            {
//                                echo '<img src="' . $arrComment['img'] . '" class="img-responsive">';
//                            }

        echo '<div class="btn-group">
                                      <button id="' . $arrComment->getId () . '" class="btn btn-white btn-xs ' . $likeClass . ' post"><i class="fa fa-thumbs-up"></i> Like this! (' . $arrComment->getLikes () . ')</button>
                                          <a href="#" id="' . $arrComment->getId () . '" class="showLikes" type="post">' . $likes . ' ' . ($likeCount > 0 ? ' and ' . $likeCount . ' others' : ' liked this ') . ' </a>
                                      <button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button>
                                      <button class="btn btn-white btn-xs SharePost"><i class="fa fa-share"></i> Share</button>
                                  </div>
                              </div>';

        echo '<div class="social-footer" id="' . $arrComment->getId () . '">';

        $comments = $arrComment->getArrComments ();

        if ( count ($comments) > 0 ):


            foreach ($comments as $count => $comment):

                $class = $count >= $totalCommentsToDisplay ? 'd-none' : '';

                $userCommentLikes = [];
                $likeCommentCount = 0;
                $commentLikes = '';
                $likeCommentClass = 'like';

                $arrCommentLikes = $comment->getArrLikes ();

                if ( !empty ($arrCommentLikes) )
                {

                    $userCommentLikes = array_reduce ($arrCommentLikes, function ($reduced, $current) {

                        $fullName = $current->getFirstName () . ' ' . $current->getLastName ();

                        $reduced[$current->getUsername ()] = $fullName;
                        return $reduced;
                    });

                    $likeCommentClass = !empty ($userCommentLikes) && array_key_exists ($_SESSION['user']['username'], $userCommentLikes) ? 'unlike' : $likeClass;
                    $commentLikes = implode (',', array_slice ($userCommentLikes, 0, 2));
                    $likeCommentCount = count ($usersLikes) - 2;
                }

                if ( $count === $totalCommentsToDisplay )
                {
                    echo '<a id="' . $arrComment->getId () . '" href="#" class="viewMore">View More Comments</a>';
                }

                echo '<div class="social-comment comment-a1 ' . $class . '">
                                                <a href="profile.php?user='.$comment->getUserId ().'" class="pull-left">
                                                    <img alt="image" src="uploads/profile/' . $comment->getUsername () . '.jpg">
                                                </a>
                                                <div class="media-body">
                                                    <a href="profile.php?user='.$comment->getUserId ().'">
                                                        ' . $comment->getAuthor () . ' <br>
                                                    </a>
                                                    <small date="' . $comment->getCreated () . '" class="text-muted timeAgo">' . blab_time_ago ($comment->getCreated ()) . '</small> <br>
                                                    <span style="font-size:14px;">
                                                   ' . $comment->getComment () . '
                                                       </span>
                                                    
                                                </div>
                                                
<div class="btn-group">
                                      <button comment-id="' . $comment->getId () . '" id="' . $arrComment->getId () . '" class="btn btn-white btn-xs ' . $likeCommentClass . ' comment"><i class="fa fa-thumbs-up"></i> Like this! (' . $comment->getLikes () . ')</button>
                                          <a href="#" class="showLikes" id="' . $comment->getId () . '" type="comment">' . $commentLikes . ' ' . ($likeCommentCount > 0 ? ' and ' . $likeCommentCount . ' others' : ' liked this ') . '</a>
                                      <button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button>
                                      <button class="btn btn-white btn-xs"><i class="fa fa-share"></i> Share</button>
                                  </div>
                                            </div>';


            endforeach;
        endif;
        echo '<div class="social-comment">
                                <a href="" class="pull-left">
                                    <img alt="image" src="img/a3.jpg">
                                </a>
                                <div class="media-body">
                                    <textarea comment-id="' . $arrComment->getId () . '" class="form-control reply-comment" placeholder="Write comment..."></textarea>
                                </div>
                            </div>';



        echo '</div>';


        echo '</div>';

        $postCount++;
    }

    return $html;
}
