<link href="/blab/public/css/group.css" rel="stylesheet" type="text/css">

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">

        <?php
        $totalCommentsToDisplay = 1;

        $friendIds = [];

        foreach ($arrFriendList as $friend) {
            $friendIds[] = $friend->getId ();
        }
        ?>

        <input type="hidden" id="currentPageId" value="<?= $objPage->getUrl () ?>">
        <input type="hidden" id="currentPageName" value="<?= $objPage->getName () ?>">
        <input type="hidden" id="currentPageDescription" value="<?= $objPage->getDescription () ?>">
        <input type="hidden" id="currentPageImage" value="<?= $objPage->getFileLocation () ?>">
        <input type="hidden" id="currentWebsiteUrl" value="<?= $objPage->getWebsiteUrl () ?>">
        <input type="hidden" id="currentPostcode" value="<?= $objPage->getPostcode () ?>">
        <input type="hidden" id="currentTelephone" value="<?= $objPage->getTelephoneNo () ?>">
        <input type="hidden" id="currentAddress" value="<?= $objPage->getAddress () ?>">
        <input type="hidden" id="currentPrivacy" value="public">

        <div class="col-lg-3">

            <?php $this->partial ("templates/pageDetails", ["objPage" => $objPage]); ?>
        </div>

        <div class = "col-lg-6">
            <div class = "ibox">
                <div class = "ibox-content">
                    <div class = "text-center m-t-md">
                        <!--timeline profile picture -->

                        <div class = "gprofilephoto_wrap">
                            <div id = "vcoverPic" style = "display:block; width:100%; height:100%;">
                                <div class = "gvprofilephoto" style = "background-image: url('<?= $objPage->getFileLocation () ?>');" onclick = "vpb_popup_photo_box ('michaelhampton', '1', '1', '<?= $objPage->getFileLocation () ?>');">
                                </div>
                            </div>

                            <div class = "gvprofilephoto_editer" data-backdrop = "static" data-toggle = "modal" data-target = "#add-page-photo">
                                <i class = "fa fa-camera"></i> Update Photo
                            </div>

                            <div class = "vthe_group_dname vpb_profile_name" style = "cursor:text;">
                                <span id = "p_page_name"><?= $objPage->getName ()
            ?></span><br>

                            </div>
                        </div>


                        <div id="group_page_menu" class="group_manin_menu_wrapper">
                            <div id="not_deleting_group" style="width:100%; display:block;">
                                <div style="clear:both;"></div>
                                <span id="g_discussion" class="group_menu_wrapper_active" onclick="vpb_show_status_updates ();">Discussion</span>

                                <span class="group_menu_wrapper" onclick="vpb_load_page_photos ('<?= $objPage->getName () ?>');">Photos</span>
                                <span class="group_menu_wrapper" onclick="vpb_load_page_reviews ('<?= $objPage->getUrl () ?>');">Reviews</span>

                                <span id="g_videos" class="group_menu_wrapper" onclick="vpb_show_page_videos ();">Videos</span>

                                <span id="g_videos" class="group_menu_wrapper" onclick="vpb_shoq_report_this_page_box ('Michael hampton', 'michaelhampton', 'bluetiger_uan@yahoo.com', '<?= $objPage->getId () ?>', '<?= $objPage->getName () ?>')">Report Group</span>             
                                <span id="vpb_get_all_the_group_confirmation_box" class="group_menu_wrapper"></span> 

                                <?php if ( (int) $objPage->getUserId () === (int) $_SESSION['user']['user_id'] ): ?> 
                                    <span onclick="vpb_confirm_delete_current_page_details ('<?= $objPage->getUrl () ?>', 'michaelhampton', '<?= $objPage->getName () ?>');" style="float:right !important;" class="group_menu_wrapper vasplus_tooltip_icons" original-title="Delete this Page"><i class="fa fa-remove v_edit_group_details"></i></span>
                                    <span onclick="vpb_set_current_page_details ('<?= $objPage->getUrl () ?>');" style="float:right !important;border-left: 1px solid #e5e5e5;" class="group_menu_wrapper vasplus_tooltip_icons" original-title="Edit Page Details"><i class="fa fa-pencil-square v_edit_group_details"></i></span>
                                <?php endif; ?>

                            </div>
                            <div style="clear:both;"></div>


                        </div>




                        <div class="uploadedImage">

                        </div>

                    </div>
                </div>
            </div>

            <div id="vasplus_wall_status_updates">
                <div class="row" style="">
                    <div class="ibox">
                        <div class="ibox-content">
                            <?php
                            if ( trim ($objPage->getPostcode ()) !== "" )
                            {
                                echo ' <div id="status">Loading.............</div>
            <div id="map"></div>';
                            }
                            ?>
                        </div>
                    </div>
                </div>


                <span id="deleting_page"></span>





                <?php
                if ( (int) $objPage->getUserId () === (int) $_SESSION['user']['user_id'] )
                {
                    $this->partial ("templates/postBox", ["form" => "groupcommentform"]);
                }
                ?>

                <div class="row">
                    <?php //$this->partial ("templates/sortingBox");      ?>
                </div>



                <div id="posts-list" style="margin-top: 20px;">
                    <?php
                    $this->partial (
                            "templates/posts", [
                        "arrPosts" => $arrPosts,
                        "totalCommentsToDisplay" => $totalCommentsToDisplay
                            ]
                    );
                    ?>
                </div>
            </div>



            <!-- Display this Page Group Videos Starts -->
            <div class="vmiddle_other" id="vasplus_group_page_videos">
                <div class="vmiddle_other_title vprofile_o_title">
                    <div style="float:left;">Videos · <span class="vtotals">0</span></div>
                    <div style="float:right; font-weight:normal !important; font-size:13px !important;">
                        <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" title="Close" onClick="vpb_show_status_updates ();">×</button>
                    </div>
                    <div style="clear:both;"></div>
                </div>


                <div id="vpb_get_all_the_groups_videos"><div style="padding:10px;" title="Loading..." class="btn_loading">Loading<span class="dots"><span>.</span><span>.</span><span>.</span></span></div></div>

            </div>
            <!-- Display this Page Group Videos Ends -->

            <!-- Display this Page Group Reviews Starts -->
            <div class="vmiddle_other" id="vasplus_group_page_reviews">
                <div class="vmiddle_other_title vprofile_o_title">
                    <div style="float:left;">Reviews · <span class="vtotals">0</span></div>
                    <div style="float:right; font-weight:normal !important; font-size:13px !important;">
                        <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" title="Close" onClick="vpb_show_status_updates ();">×</button>
                    </div>
                    <div style="clear:both;"></div>
                </div>


                <div id="vpb_get_all_the_groups_videos" style="padding:10px;">
                    <h3>Add Review</h3>

                    <div class='movie_choice'>
                        Rate: <?= $objPage->getName () ?>
                        <div id="r2" class="rate_widget">
                            <div class="star_1 ratings_stars"></div>
                            <div class="star_2 ratings_stars"></div>
                            <div class="star_3 ratings_stars"></div>
                            <div class="star_4 ratings_stars"></div>
                            <div class="star_5 ratings_stars"></div>
                            <div class="total_votes">vote data</div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Review</label>
                        <textarea class="form-control" id="theReview" placeholder="Your review" rows="3"></textarea>
                    </div>
                    <button class="btn btn-primary btn-block SaveReview">Save</button>

                    <div class="col-lg-12">
                        <?php
                        $this->partial (
                                "templates/posts", [
                            "arrPosts" => $arrReviews,
                            "totalCommentsToDisplay" => $totalCommentsToDisplay
                                ]
                        );
                        ?>
                    </div>


                </div>

            </div>
            <!-- Display this Page Group Reviews Ends -->

            <!-- Display this Page Group Photos Starts -->
            <div class="vmiddle_other" id="vasplus_group_page_photos">
                <div class="vmiddle_other_title vprofile_o_title">
                    <div style="float:left;">Photos · <span class="vtotals"><?= count ($arrPhotos) ?></span></div>
                    <div style="float:right; font-weight:normal !important; font-size:13px !important;">
                        <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" title="Close" onClick="vpb_show_status_updates ();">×</button>
                    </div>
                    <div style="clear:both;"></div>
                </div>


                <div id="vpb_get_all_the_groups_photos">
                    <div class="lightBoxGallery">
                        <?php
                        foreach ($arrPhotos as $key => $arrPhoto) {

                            if ( $key === 0 )
                            {
                                $id = $arrPhoto->getId ();
                            }

                            echo '<input type="hidden" id="hidden_photo_link_' . $id . '_' . ($key + 1) . '" value="' . $arrPhoto->getFileLocation () . '">';

                            echo '<a href="#"  onclick="vpb_popup_photo_box(\'' . $arrPhoto->getId () . '\', \'' . count ($arrPhotos) . '\', \'' . ($key + 1) . '\', \'' . $arrPhoto->getFileLocation () . '\');" title="Image from Unsplash" data-gallery=""><img src="' . $arrPhoto->getFileLocation () . '"></a>';
                        }
                        ?>

                    </div>
                </div>

            </div>
            <!-- Display this Page Group Photos Ends -->


        </div>

        <div class="col-lg-3">
            <div class="ibox">
                <div class="ibox-content">
                    <div id="vpb_get_all_the_users_groups">

                    </div>
                    <br clear="all">
                </div>
            </div>

        </div>

        <script src="/blab/public/js/geocomplete.js"></script>
        <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA1COtE7cJxfGxNWiTjEgtSNhbvDBCiiqQ&libraries=places"></script>
        <script src="/blab/public/js/geocomplete.js"></script>
        <script src="/blab/public/js/newsFeed.js"></script>
        <script src="/blab/public/js/page.js"></script>

        <script>

                            var lat = '<?= $lat ?>';
                            var lng = '<?= $lng ?>';


                            var groupId = '<?= $url ?>';
                            var groupName = '<?= $objPage->getName () ?>';

                            var selectedImageType = "page";
                            var selectedImageId = groupId;

                            success (lat, lng);

                            function success (lat, lng)
                            {
                                var s = document.querySelector ('#status');
                                if (s.className == 'success')
                                {
                                    return;
                                }
                                s.className = 'Success';
                                var mapcanvas = document.createElement ('div');
                                mapcanvas.id = 'mapcanvas';
                                mapcanvas.style.height = '100%';
                                mapcanvas.style.width = '100%';
                                document.querySelector ('#map').appendChild (mapcanvas);
                                $ ("#status").hide ();
                                var latlng = new google.maps.LatLng (lat, lng);
                                var myOptions = {
                                    zoom: 15,
                                    center: latlng,
                                    mapTypeControl: false,
                                    navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
                                    mapTypeId: google.maps.MapTypeId.ROADMAP
                                };
                                var map = new google.maps.Map (document.getElementById ("mapcanvas"), myOptions);
                                var marker = new google.maps.Marker ({
                                    position: latlng,
                                    map: map,
                                    title: "You are here!"
                                });
                                //            $.cookie ("MyLat", position.coords.latitude); // Storing latitude value
                                //            $.cookie ("MyLon", position.coords.longitude); // Storing longitude value
                            }

                            function error (msg)
                            {
                                var s = document.querySelector ('#status');
                                s.innerHTML = typeof msg == 'string' ? msg : "failed";
                                s.className = 'Fail';
                            }

                            //        if (navigator.geolocation)
                            //        {
                            //            navigator.geolocation.getCurrentPosition (success, error);
                            //        }
                            //        else
                            //        {
                            //            error ('Not supported'); //HTML Support
                            //        }

                            function readURL (input)
                            {
                                if (input.files && input.files[0])
                                {
                                    var reader = new FileReader ();

                                    reader.onload = function (e)
                                    {
                                        $ ('.uploadedImage').append ('<img src="' + e.target.result + '">');

                                    };

                                    reader.readAsDataURL (input.files[0]);
                                    $ (".currentImage").remove ();
                                    $ ("#groupImage").submit ();
                                }
                            }

                            //Jquery Code 
                            $ (document).ready (function ()
                            {
                                //        $ ("#check").click (function ()
                                //        {
                                //            var lat = $.cookie ("MyLat");
                                //            var lon = $.cookie ("MyLon");
                                //            alert ('Latitued: ' + lat);
                                //            alert ('Longitude: ' + lon);
                                //            var url = "http://maps.googleapis.com/maps/api/geocode/json?latlng=" + lat + "," + lon + "&sensor=false";
                                //            alert ('Google Map API: ' + url);
                                //            //Get Json Request Here
                                //        });
                                $ (document).off ("click", "#timelineProfilePic");
                                $ (document).on ('click', '#timelineProfilePic', function ()
                                {
                                    $ ("#profileimgaa").click ();

                                });

                                $ (document).off ("change", "#profileimgaa");
                                $ (document).on ('change', '#profileimgaa', function ()
                                {

                                    readURL (this);
                                });

                                $ (document).off ("submit", "#groupImage");
                                $ (document).on ('submit', '#groupImage', function ()
                                {
                                    //stop submit the form, we will post it manually.
                                    event.preventDefault ();
                                    // Get form
                                    var form = $ ('#groupImage')[0];
                                    // Create an FormData object
                                    var data = new FormData (form);
                                    data.append ("groupId", groupId);
                                    data.append ("groupName", groupName);

                                    alert ("OK");

                                    // If you want to add an extra field for the FormData
                                    // disabled the submit button
                                    $.ajax ({
                                        type: "POST",
                                        enctype: 'multipart/form-data',
                                        url: "/blab/page/updatePageImage",
                                        data: data,
                                        processData: false,
                                        contentType: false,
                                        cache: false,
                                        success: function (response)
                                        {

                                            formatResponse (response, 'The image was saved successfully.');
                                            return false;
                                        },
                                        error: function (e)
                                        {


                                        }
                                    });

                                    return false;
                                });

                            });

                            function handleGroupSubmit ()
                            {
                                alert ("1");

                                var mentions = $ ('.mentions').mentionsInput ('getMentions');

                                var blkstr = [];
                                $.each (mentions, function (idx2, val2)
                                {

                                    blkstr.push (val2.uid);
                                });

                                var tags = blkstr.join (", ");

                                var form = $ (this);
                                if (form.find ('#comment').val () === "")
                                {
                                    showErrorMessage ("You must enter a comment");
                                    return false;
                                }

                                var data = {
                                    "comment": form.find ('#comment').val (),
                                    "pageUrl": groupId,
                                    tags: tags
                                };
                                postGroupComment (data);
                                return false;
                            }

                            function postGroupComment (data)
                            {
                                alert ("Yes");

                                // send the data to the server
                                $.ajax ({
                                    type: 'POST',
                                    url: '/blab/page/postPageComment',
                                    data: data,
                                    headers: {
                                        'X-Requested-With': 'XMLHttpRequest'
                                    },
                                    success: postGroupSuccess,
                                    error: postGroupError
                                });
                            }

                            function postGroupSuccess (data, textStatus, jqXHR)
                            {
                                $ ('#groupcommentform').get (0).reset ();
                                load_unseen_notification ();
                                $ ("#posts-list").prepend (data);
                                return false;
                            }

                            function postGroupError (jqXHR, textStatus, errorThrown)
                            {
                                // display error
                                showErrorMessage (errorThrown);
                            }

                            function displayGroupComment (data)
                            {
                                var commentHtml = createComment (data);
                                var commentEl = $ (commentHtml);
                                commentEl.hide ();
                                var postsList = $ ('#posts-list');
                                postsList.addClass ('has-comments');
                                postsList.prepend (commentEl);
                                commentEl.slideDown ();
                            }

                            function createGroupComment (data)
                            {
                                var data = $.parseJSON (data);

                                var html = '<div class="social-feed-box">' +
                                        '<div class="pull-right social-action dropdown">' +
                                        '<button data-toggle="dropdown" class="dropdown-toggle btn-white">' +
                                        '<i class="fa fa-angle-down"></i>' +
                                        '</button>' +
                                        '<ul class="dropdown-menu m-t-xs">' +
                                        '<li><a href="#">Config</a></li>' +
                                        '</ul>' +
                                        '</div>' +
                                        '<div class="social-avatar">' +
                                        '<a href="" class="pull-left">' +
                                        '<img alt="image" src="/blab/public/uploads/profile/' + data.username + '.jpg">' +
                                        '</a>' +
                                        '<div class="media-body">' +
                                        '<a href="#">' +
                                        data.author +
                                        '</a>' +
                                        '<small date="' + data.date_added + '" class="text-muted timeAgo">' + timeSince (data.date_added) + '</small>' +
                                        '</div>' +
                                        '</div>' +
                                        '<div class="social-body">' +
                                        '<p>' +
                                        data.comment +
                                        '</p>' +
                                        '<div class="btn-group">' +
                                        '<button id="' + data.id + '" class="btn btn-white btn-xs like post"><i class="fa fa-thumbs-up"></i> Like this!</button>' +
                                        '<br><a href="#" class="showLikes" type="post">Liked by Mike</a>' +
                                        '<button class="btn btn-white btn-xs"><i class="fa fa-comments"></i> Comment</button>' +
                                        '<button class="btn btn-white btn-xs Share" messageid="' + data.id + '"><i class="fa fa-share"></i> Share</button>' +
                                        '</div>' +
                                        '</div>' +
                                        '<div class="social-footer" id="' + data.id + '">' +
                                        '<div class="social-comment">' +
                                        '<a href="" class="pull-left">' +
                                        '<img alt="image" src="/blab/public/img/a3.jpg">' +
                                        '</a>' +
                                        '<div class="media-body">' +
                                        '<textarea comment-id="' + data.id + '" class="form-control reply-comment" placeholder="Write comment..."></textarea>' +
                                        '</div>' +
                                        '</div>' +
                                        '</div>';
                                return html;
                            }

                            $ (document).ready (function ()
                            {
                                $ ('#groupcommentform').submit (handleGroupSubmit);
                            });






        </script>