<style>
    .reg_name {
        max-width: 200px;
    }

    .box__file {
        width: 0.1px;
        height: 0.1px;
        opacity: 0;
        overflow: hidden;
        position: absolute;
        z-index: -1;
    }

    .box__button {
        font-weight: 700;
        color: #e5edf1;
        background-color: #39bfd3;
        display: none;
        padding: 8px 16px;
        margin: 40px auto 0;
    }

    .box__uploading, .box__success, .box__error {
        display: none;
    }


    .box.has-advanced-upload .box__dragndrop {
        display: inline;
    }

    .is-dragover {
        background-color: grey;
    }
</style>

<div class="row">
    <div class="col-lg-8">
        <div class="ibox float-e-margins">
            <div class="ibox-title" style="background-color: #EEE;">
                <h5>Add Contact</h5>

            </div>
            <div class="ibox-content">

                <form method="post" action="/blab/index/testPost" name="registration_form" id='registration_form' class="form-inline box has-advanced-upload" enctype="multipart/form-data">
                    <div class="row" style="margin-bottom:12px;">
                        <div class="form-group col-xs-6">
                            <label for="exampleInputEmail2" class="col-xs-4">First Name</label>
                            <input type="text" placeholder="First Name" name="firstName" id="firstName" class="form-control">
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="exampleInputPassword2" class="col-xs-4">Last Name</label>
                            <input type="text" placeholder="Last Name" name="lastName" id="lastName" class="form-control">
                        </div>
                    </div>

                    <div class="row" style="margin-bottom:12px;">
                        <div class="form-group col-xs-6">
                            <label for="exampleInputEmail2" class="col-xs-4">First Name</label>
                            <input type="text" placeholder="First Name" id="exampleInputEmail2" class="form-control">
                        </div>

                        <div class="form-group col-xs-6">
                            <label for="exampleInputPassword2" class="col-xs-4">Contact Type</label>
                            <select name="jobType" id="jobType" class="form-control">
                                <option value="">Select Option</option>
                                <option value="test">Test</option>
                                <option value="test2">Test 2</option>
                            </select>
                        </div>
                    </div>

                    <div class="row" style="margin-bottom: 12px;">
                        <div class="form-group col-xs-6 pull-left">
                            <div class="box__input">

                                <input type="file" name="files[]" id="file" class="box__file" data-multiple-caption="{count} files selected" multiple="">

                                <button type="submit" class="box__button">Upload</button>
                            </div>

                            <div class="col-lg-12 pull-left dragBox" style="border: 1px dotted #000; height: 100px; padding: 12px;">
                                <svg class="box__icon" xmlns="http://www.w3.org/2000/svg" width="50" height="43" viewBox="0 0 50 43"><path d="M48.4 26.5c-.9 0-1.7.7-1.7 1.7v11.6h-43.3v-11.6c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v13.2c0 .9.7 1.7 1.7 1.7h46.7c.9 0 1.7-.7 1.7-1.7v-13.2c0-1-.7-1.7-1.7-1.7zm-24.5 6.1c.3.3.8.5 1.2.5.4 0 .9-.2 1.2-.5l10-11.6c.7-.7.7-1.7 0-2.4s-1.7-.7-2.4 0l-7.1 8.3v-25.3c0-.9-.7-1.7-1.7-1.7s-1.7.7-1.7 1.7v25.3l-7.1-8.3c-.7-.7-1.7-.7-2.4 0s-.7 1.7 0 2.4l10 11.6z"></path></svg>
                                <label for="file"><strong>Choose a file</strong><span class="box__dragndrop"> or drag it here</span>.</label>
                            </div>

                            <ul class="filelist"></ul>
                            <div class="box__uploading">Uploading…</div>
                            <div class="box__success">Done! <a href="https://css-tricks.com/examples/DragAndDropFileUploading//?submit-on-demand" class="box__restart" role="button">Upload more?</a></div>
                            <div class="box__error">Error! <span></span>. <a href="https://css-tricks.com/examples/DragAndDropFileUploading//?submit-on-demand" class="box__restart" role="button">Try again!</a></div>
                        </div>

                        <div class="form-group col-xs-6 pull-left FilePreviews">

                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
        <div class="ibox float-e-margins">
            <div class="ibox-title" style="background-color: #EEE;">
                <h5>Contact Types</h5>

            </div>
            <div class="ibox-content">

                <div class="row addContactType" style="margin-bottom:12px;">
                    <div class="form-group col-xs-5">
                        <label for="exampleInputEmail2" class="">Contact Type</label>
                        <select id="contactType" class="form-control">
                            <option value="">Select Option</option>
                            <option value="1">Email</option>
                            <option value="2">Mobile</option>
                            <option value="3">Telephone</option>
                        </select>
                    </div>

                    <div class="form-group col-xs-5">
                        <label for="exampleInputPassword2" class="col-xs-2">Text</label>
                        <input type="text" placeholder="Text" id="textLabel" class="form-control">
                    </div>

                    <div class="col-xs-1">
                        <button style="margin-top: 26px;" class="btn btn-sm btn-primary pull-right m-t-n-xs addContactTypeToList" type="button"><strong>+</strong></button>
                    </div>
                </div>

                <div class="row showContactType" style="margin-bottom:12px;">

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary SaveNewContactType">Save changes</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <h1 class="page-header">jQuery Chained Select</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-3">
            <form action="" id="addToCart">
                <div class="form-group">
                    <select name="color" id="size" class="form-control">
                        <option value="">Size</option>
                        <option value="Small">Small</option>
                        <option value="Medium">Medium</option>
                        <option value="Large">Large</option>
                        <option value="X-Large">X-Large</option>
                    </select>
                </div>
                <div class="form-group">
                    <select name="color" id="color" class="form-control" disabled>
                        <option value="">Color</option>
                        <option value="Red">Red</option>
                        <option value="Blue">Blue</option>
                        <option value="Green">Green</option>
                    </select>
                </div>
                <div class="form-group">
                    <select name="qty" id="qty" class="form-control" disabled>
                        <option value="">Quantity</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" id="submit" class="btn btn-default" disabled><i class="glyphicon glyphicon-shopping-cart"></i> Add to Cart</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
// feature detection for drag&drop upload

    var maxNoOfFiles = 10;
    var thumbnailWidth = "100px";
    var dragEnabled = true;
    showPreview = true;
</script>

<script src="/blab/public/js/upload.js"></script>

<script>

    size = chainSelect ('select#size', '#color');
    color = chainSelect ('select#color', '#qty');
    qty = chainSelect ('select#qty', '#submit');

    function chainSelect (current, target)
    {
        var value1 = $ (current).on ('change', function ()
        {
            if ($ (this).find (':selected').val () != '')
            {
                $ (target).removeAttr ('disabled');
                var value = $ (this).find (':selected').text ();
            }
            else
            {
                $ (target).prop ('disabled', 'disabled').val (null);
            }
            return value;
        });
        return value1;
    }

    $ (".box").on ("submit", function (e)
    {

        if ($ (this).hasClass ('is-uploading'))
        {
            return false;
        }

        $ (this).addClass ('is-uploading').removeClass ('is-error');

        e.preventDefault ();

        // gathering the form data
        var ajaxData = new FormData ($ (this).get (0));

        console.log ("Mike");
        console.log (ajaxData);
        console.log (droppedFiles);

        var $this = $ (this);

        if (droppedFiles)
        {
            $.each (droppedFiles, function (i, file)
            {
                if ($.trim (file.name) !== "")
                {
                    ajaxData.append ($this.find ('input[type="file"]').attr ('name'), file);
                }
            });
        }

        var attendees = calculate ();
        ajaxData.append ("attendees", JSON.stringify (attendees));



        // ajax request
        $.ajax (
                {
                    url: $this.attr ('action'),
                    type: $this.attr ('method'),
                    data: ajaxData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    complete: function ()
                    {
                        $this.removeClass ('is-uploading');
                    },
                    success: function (data)
                    {
                        alert (data);
                        $this.addClass (data.success == true ? 'is-success' : 'is-error');
                        if (!data.success)
                            $errorMsg.text (data.error);
                    },
                    error: function ()
                    {
                        alert ('Error. Please, contact the webmaster!');
                    }
                });
    });

    /**
     * 
     * @param {type} contactType
     * @param {type} label
     * @returns {undefined}
     */
    function createInput (contactType, contactTypeId, label)
    {
        var formgroup = $ ("<div/>", {
            class: "form-group col-lg-12"
        }).css ("margin-bottom", "12px");

        formgroup.append ($ ("<label>", {
            class: "col-sm-2 control-label",
            text: contactType
        }));

        var colsm = $ ("<div/>", {
            class: "col-sm-8"
        });

        var input = $ ("<input/>", {
            type: "text",
            class: "form-control contacttype pull-left",
            id: "nameId",
            typeid: contactTypeId,
            name: "contacttypes[]",
            value: label
        }).css ("width", "90%");

        var deleteButton = $ ("<a>", {
            class: "deleteContactType",
            html: "<i class=\"fa fa-times-circle\"></i>"
        }).css ({
            'margin': '10px 0px 0px 10px',
            'float': 'left'
        });

        colsm.append (input);
        colsm.append (deleteButton);
        formgroup.append (colsm);
        $ (".showContactType").append (formgroup);
    }


    function calculate ()
    {
        var attendees = $ ('.contacttype').map (function ()
        {
            return  {
                contacttype: $ (this).attr ('typeid'),
                label: $ (this).val (),
            }
        }).get ();

        return attendees;
    }

    $ (document).off ("click", ".deleteContactType");
    $ (document).on ("click", ".deleteContactType", function ()
    {
        $ (this).parent ().parent ().remove ();
    });

    $ (".addContactTypeToList").on ("click", function ()
    {
        var contactTypeId = $ ("#contactType").val ();

        if (!contactTypeId)
        {
            alert ("You must select a contact type");
            return false;
        }

        var contactType = $ ("#contactType").find ("option:selected").text ();

        if (!contactType)
        {
            alert ("You must select a contact type");
            return false;
        }

        var label = $ ("#textLabel").val ();

        if (!label)
        {
            alert ("You must enter some text");
            return false;
        }

        createInput (contactType, contactTypeId, label);
        $ ("#textLabel").val ("");
        $ ('#contactType').prop ('selectedIndex', 0);
    });
</script>










<!--<link rel="stylesheet" type="text/css" href="/blab/public/css/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="/blab/public/css/slick/slick-theme.css"/>

<hr/>
<h2>Multiple Items</h2>
<div class="slider multiple-items">
    <div><h3>1</h3></div>
    <div><h3>2</h3></div>
    <div><h3>3</h3></div>
    <div><h3>4</h3></div>
    <div><h3>5</h3></div>
    <div><h3>6</h3></div>
    <div><h3>7</h3></div>
    <div><h3>8</h3></div>
    <div><h3>9</h3></div>
</div>

<script src="/blab/public/js/slick.js"></script>

<script>
    $ ('.multiple-items').slick ({
        infinite: true,
        slidesToShow: 3,
        slidesToScroll: 3
    });

</script>-->