<link rel="stylesheet" type="text/css" href="/blab/public/css/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="/blab/public/css/slick/slick-theme.css"/>

<hr/>
<h2>Multiple Items</h2>
<div class="slider multiple-items">
    <div><h3>1</h3></div>
    <div><h3>2</h3></div>
    <div><h3>3</h3></div>
    <div><h3>4</h3></div>
    <div><h3>5</h3></div>
    <div><h3>6</h3></div>
    <div><h3>7</h3></div>
    <div><h3>8</h3></div>
    <div><h3>9</h3></div>
</div>

<script src="/blab/public/js/slick.js"></script>

<script>
    $ ('.multiple-items').slick ({
        infinite: true,
        slidesToShow: 3,
        slidesToScroll: 3
    });

</script>