<style type="text/css">
    .btn-file {
        position: relative;
        overflow: hidden;
    }

    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        outline: none;
        background: white;
        cursor: inherit;
        display: block;
    }

    .img-zone {
        /*        background-color: #F2FFF9;
                border: 5px dashed #4cae4c;
                border-radius: 5px;
                padding: 20px;*/
    }

    .img-zone h2 {
        margin-top: 0;
    }

    .progress, #img-preview {
        margin-top: 15px;
    }
</style>


<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Collaps panels</h5>

            </div>
            <div class="ibox-content">
                <div class="panel-body">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h5 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Documents</a>
                                </h5>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in">
                                <div class="panel-body" id="documents-panel">

                                    <div class="col-sm-2">
                                        <h2><i class="glyphicon glyphicon-camera"></i></h2>
                                        <span class="btn btn-success btn-sm btn-file">
                                            Click to Open File Browser<input type="file" multiple="" accept="image/*">
                                        </span>
                                    </div>

                                    <div class="progress hidden">
                                        <div style="width: 0%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="0" role="progressbar" class="progress-bar progress-bar-success progress-bar-striped active">
                                            <span class="sr-only">0% Complete</span>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    $ (document).ready (function ()
    {
        var img_zone = document.getElementById ('documents-panel'),
                collect = {
                    filereader: typeof FileReader != 'undefined',
                    zone: 'draggable' in document.createElement ('span'),
                    formdata: !!window.FormData
                },
        acceptedTypes = {
            'image/png': true,
            'image/jpeg': true,
            'image/jpg': true,
            'image/gif': true
        };

        // Function to show messages
        function ajax_msg (status, msg)
        {
            var the_msg = '<div class="alert alert-' + (status ? 'success' : 'danger') + '">';
            the_msg += '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>';
            the_msg += msg;
            the_msg += '</div>';
            $ (the_msg).insertBefore (img_zone);
        }

        // Function to upload image through AJAX
        function ajax_upload (files)
        {
            $ ('.progress').removeClass ('hidden');
            $ ('.progress-bar').css ({
                "width": "0%"
            });
            $ ('.progress-bar span').html ('0% complete');

            var formData = new FormData ();
            //formData.append('any_var', 'any value');
            for (var i = 0; i < files.length; i++) {
                //formData.append('img_file_' + i, files[i]); 
                formData.append ('img_file[]', files[i]);
            }

            $.ajax ({
                url: "/blab/index/testPost2", // Change name according to your php script to handle uploading on server
                type: 'post',
                data: formData,
                processData: false,
                contentType: false,
                error: function (request)
                {
                    ajax_msg (false, 'An error has occured while uploading photo.');
                },
                success: function (response)
                {
                    try {

                        var objResponse = $.parseJSON (response);

                        if (objResponse.sucess == 1)
                        {
                            var data = objResponse.data;

                            if (!data.img)
                            {
                                ajax_msg (false, 'An error has occured while uploading photo.');
                                return false;
                            }
                            
                            var img_preview = $ ('#documents-panel');
                            var col = '.col-sm-2';
                            $ ('.progress').addClass ('hidden');
                            var photos = $ ('<div class="photos"></div>');
                            $ (photos).html (data.img);
                            var lt = $ (col, photos).length;
                            $ ('col', photos).hide ();
                            $ (img_preview).append (photos.html ());
                            $ (col + ':lt(' + lt + ')', img_preview).fadeIn (2000);
                        }
                        else
                        {
                            ajax_msg (false, objResponse.message);
                        }

                    } catch (e) {
                        ajax_msg (false, e);
                    }
                },
                progress: function (e)
                {
                    if (e.lengthComputable)
                    {
                        var pct = (e.loaded / e.total) * 100;
                        $ ('.progress-bar').css ({
                            "width": pct + "%"
                        });
                        $ ('.progress-bar span').html (pct + '% complete');
                    }
                    else
                    {
                        console.warn ('Content Length not reported!');
                    }
                }
            });
        }

        // Call AJAX upload function on drag and drop event
        function dragHandle (element)
        {
            element.ondragover = function ()
            {
                $("#documents-panel").css("background-color", "#EEE");
                return false;
            };
            element.ondragend = function ()
            {
                return false;
            };
            element.ondrop = function (e)
            {
                e.preventDefault ();
                $("#documents-panel").css("background-color", "#FFF");
                ajax_upload (e.dataTransfer.files);
            };
        }

        if (collect.zone)
        {
            dragHandle (img_zone);
        }
        else
        {
            alert ("Drag & Drop isn't supported, use Open File Browser to upload photos.");
        }

        // Call AJAX upload function on image selection using file browser button
        $ (document).on ('change', '.btn-file :file', function ()
        {
            ajax_upload (this.files);
        });

        // File upload progress event listener
        (function ($, window, undefined)
        {
            var hasOnProgress = ("onprogress" in $.ajaxSettings.xhr ());

            if (!hasOnProgress)
            {
                return;
            }

            var oldXHR = $.ajaxSettings.xhr;
            $.ajaxSettings.xhr = function ()
            {
                var xhr = oldXHR ();
                if (xhr instanceof window.XMLHttpRequest)
                {
                    xhr.addEventListener ('progress', this.progress, false);
                }

                if (xhr.upload)
                {
                    xhr.upload.addEventListener ('progress', this.progress, false);
                }

                return xhr;
            };
        }) (jQuery, window);
    });
</script>