<div class="vmail_text top">
    <div style="padding:10px; padding-right:10px !important;">
        <div class="open_msg">ok</div>
        <div class="close_msg"><i onclick="vpb_refresh_mail_box ('b');" class="fa fa-arrow-circle-left" aria-hidden="true"></i></div>
    </div>
</div>


<?php
if ( !empty ($arrMessages) )
{

    foreach ($arrMessages as $objMessage) {
        ?>

        <div class="mail_contents" id="message_id_55">
            <div class="cccbody">

                <div style="display:table; width:100%;">
                    <div class="ccleft">
                        <img src="/blab/public/uploads/profile/<?= $objMessage->getUsername () ?>.jpg" class="photo" align="absmiddle">
                        <div class="names"><?= $objMessage->getAuthor () ?></div>
                        <div style="clear:both;"></div>
                        <span class="small_date" title="Thursday 19th of April 2018 4:55:28 am"><?= $objMessage->getDate () ?></span>
                        <span class="sent_via">Sent to: The blab </span>
                    </div>


                    <div class="ccright">
                        <span class="big_date" title="Thursday 19th of April 2018 4:55:28 am"><?= $objMessage->getDate () ?></span> 	

                        <div class="dropdown" style="display:inline-block; position:relative;">
                            <button class="btn btn-default btn-sm dropdown-toggle" type="button" data-toggle="dropdown"><span class="caret"></span></button>
                            <!--                            <ul class="dropdown-menu" style="position:absolute;left:-130px !important;">
                                                            <li><a href="javascript:void(0);" onclick="vpb_reply ('18488251834083933');">Reply</a></li>
                                                            <li><a href="javascript:void(0);" onclick="vpb_forward ('18488251834083933', 'ok', '55');">Forward</a></li>
                                                            <li><a href="javascript:void(0);" onclick="vpb_delete_a_message ('55', '18488251834083933', 'confirm');">Delete</a></li>
                                                        </ul>-->

                            <textarea style="display:none;" id="forward_this_55"><?= $objMessage->getMessage () ?></textarea>
                        </div>
                    </div>
                </div>

                <span class="span_box">
                    <div style="clear:both;"></div>
                    <div class="vpb_msg_text"><?= $objMessage->getMessage () ?></div>



                    <div class="clear"></div>
                </span>


                <div class="clear"></div>
            </div>
        </div>

        <?php
    }
}
?>

<div style="display:block;" id="pms_reply_box">
			<input type="hidden" id="current_group_id" value="<?= $user_id ?>">
			<div style="padding:14px; background:#f6f6f6; width:100%; display:block;border-bottom:1px solid #e3e3e3;block;border-top:1px solid #e3e3e3;">
			<div id="" class="vpb_pms_bottom_header vpb_comts">
				<div id="">
				  <div class="pms_group" style="cursor:text;" onclick="document.getElementById('vpb_reply_data').focus();">
				  <div class="text">
				  <div data-placeholder="Write your message..." style="min-height:40px;" id="vpb_reply_data" class="text_box" contenteditable="true"></div>
				  </div>
				  </div>
				  <div class="modal-footer vpb_pms_footer">
					<input multiple="multiple" type="file" id="msg_add_file" style="display:none !important;" onchange="vpb_preview_files_msg(this, 'preview_msg_file');">
					<!-- Add file -->
					<span id="" class="vpb_pms_footer_wraper" onclick="vpb_add_files_to_msg();" title="Add a file"><i class="fa fa-link vfooter_icon"></i></span>
					<div class="vpb_top_line"></div>
					<div class="btn-group vpb_pms_footer_wraper_b">
					<span style="float:right; margin-left:15px;" class="btn btn-success" onclick="vpb_send_reply();">Send</span>
					<div style="clear:both;"></div>
					</div>
					</div>      
				  <!-- Footer ends -->
				  <div class="vpb_pms_video_and_photo_box">
				  <div id="preview_msg_file"></div><!-- Display added photos -->
				  </div>
			   </div>
			<div style="clear:both;"></div>
			</div>
			</div></div>