<?php
foreach ($arrPages as $arrPage) {

    $blHasRequest = false;

    $arrRequests = $arrPage->getArrFollowers ();

    if ( !empty ($arrRequests) )
    {
        foreach ($arrRequests as $objRequest) {

            if ( $objRequest->getId () === (int) $objRequest->getId () )
            {
                $blHasRequest = true;
            }
        }
    }

    $displayCancel = $blHasRequest === true ? 'block' : 'none';
    $showRequest = $blHasRequest === false ? 'block' : 'none';
    $image = trim ($arrPage->getFileLocation ()) !== "" && file_exists ($rootPath . $arrPage->getFileLocation ()) ? $arrPage->getFileLocation () : '/blab/public/img/avatar.gif';
    ?>

    <div class="vpb_groups_box notMember">
        <div class="col-lg-2 pull-left" style="padding:10px;">
            <a href="/blab/page/index/<?= $arrPage->getUrl () ?>">
                <img src="<?= $image ?>" class="img-responsive" border="0"></a>
            <div class="vproducttitle">
                <a href="/blab/page/index/<?= $arrPage->getUrl () ?>">
                    <span><?= $arrPage->getName () ?></span>
                </a>
            </div>
            <div class="vproductprice">
                <div class="vpull_left"><?= $arrPage->getFollowCount () ?> members</div>
                <div class="vpull_left"><?= $arrPage->getLikeCount () ?> likes</div>

                <div class="vpull_right">
                    <?php
                    if ( $blHasRequest === true )
                    {
                        echo '<span style="margin-top:12px;" class="label label-primary">Following</span>';
                    }
                    ?>
                </div>

                <div style="clear:both;"></div>
            </div>
        </div>
    </div>

<?php } ?>