<?php
$totalCommentsToDisplay = 1;

$friendIds = [];

foreach ($arrFriendList as $friend) {
    $friendIds[] = $friend->getId ();
}

$requestIds = [];

foreach ($arrFriendRequests as $objFriendRequest) {
    $requestIds[] = $objFriendRequest->getId ();
}
?>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="row">
                <?php
                $this->partial ("templates/profileUpload", ["arrUser" => $objUser, "friendIds" => $friendIds, "requestIds" => $requestIds]);
                $this->partial ("templates/links");
                ?>
            </div>

        </div>

        <div class="col-md-9">
            <!-- Display Group Details -->

            <div class="vprofile_o_detail" style="border-bottom:0px solid !important;">
                <div class="vprofile_o_title" style="padding:0px;">
                    <div style="float:left; padding:10px;">
                        Groups            
                    </div>
                    <div style="float:right; padding:10px;">
                        <span class="create_btn" onclick="vpb_reset_current_group_details ();"><i class="fa fa-plus" style="font-weight:normal !important;"></i> Create Group</span>

                    </div><div style="clear:both;"></div></div>
                <div style="clear:both;"></div>
            </div>

            <div style="clear:both;"></div>

            <div style="margin:0 auto; text-align:center; display:table; width: 100%;" align="center">
                <input type="hidden" id="vtotal_groups" value="<?= $totalCount ?>">
                <input type="hidden" id="vpb_groups_start" value="<?= $paginationLimit ?>">
                <input type="hidden" id="vpb_total_groups_per_load" value="<?= $paginationLimit ?>">


                <div class="row">
                    <div class="col-lg-12">
                        <div class="wrapper wrapper-content animated fadeInUp">

                            <div class="ibox">
                                <div class="ibox-title">
                                    <h5>Your Pages</h5>

                                </div>
                                <div class="ibox-content col-lg-12 pull-left" style="width:100%">
                                    <?php
                                    foreach ($arrMemberPages as $arrMemberPage) {
                                        $image = trim ($arrMemberPage->getFileLocation ()) !== "" && file_exists ($rootPath . $arrMemberPage->getFileLocation ()) ? $arrMemberPage->getFileLocation () : '/blab/public/img/avatar.gif';
                                        ?>

                                        <div class="vpb_groups_box member">
                                            <div class="col-lg-2 pull-left" style="padding:10px;">
                                                <a href="/blab/page/index/<?= $arrMemberPage->getUrl () ?>">
                                                    <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                                <div class="vproducttitle">
                                                    <a href="/blab/page/index/<?= $arrMemberPage->getUrl () ?>">
                                                        <span><?= $arrMemberPage->getName () ?></span>
                                                    </a>
                                                </div>
                                                <div class="vproductprice">
                                                    <div class="vpull_left"><?= $arrMemberPage->getFollowCount () ?> followers</div>

                                                    <div style="clear:both;"></div>
                                                </div>
                                            </div>
                                        </div>

                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="input-group vpb-the-friends-wrap" id="vpb_load_more_group_box" style="margin-top: 12px;">
                    <div style="float:left;"><span class="vpb_hover" style="color:#3b5998;" onclick="vpb_load_more_pages ();">View more pages</span></div>
                    <div style="float:right; color:#999;"><span id="v_this_members_totals"><?= count ($arrPages) ?></span> of <?= $totalCount ?></div>
                    <div style="clear:both;"></div>
                </div>

                <!-- Loading Gif -->
                <div class="input-group vpb-the-friends-wrap" style="display:none;padding:7px 10px !important;" id="vpb_loading_group_members_outer">
                    <div id="vpb_loading_group_members"></div>
                </div>


                <div class="col-md-12" style="padding:0px !important;">
                    <div class="input-group">

                        <select style="width:20%;" id="pageCategory" class="form-control">
                            <option value="">Select Category</option>
                            <?php
                            foreach ($arrCategories as $arrCategory) {
                                echo '<option value="' . $arrCategory->getId () . '">' . $arrCategory->getName () . '</option>';
                            }
                            ?>
                        </select>

                        <input style="width: 70%; margin-left: 12px;" onkeyup="vpb_load_more_pages (true)" type="text" id="searchText" placeholder="Search" class="input-sm form-control"> 
                        <span class="input-group-btn">
                            <button onclick="search ()" type="button" class="btn btn-sm btn-primary"> Go!</button> 
                        </span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="wrapper wrapper-content animated fadeInUp">

                            <div class="ibox">
                                <div class="ibox-title">
                                    <h5>Other Pages</h5>

                                </div>
                                <div class="ibox-content col-lg-12 pull-left" style="width:100%">
                                    <div id="vpb_loaded_group_members" style=" width:100%;">
                                        <?php
                                        foreach ($arrPages as $arrPage) {

                                            $blHasRequest = false;

                                            $arrRequests = $arrPage->getArrFollowers ();

                                            if ( !empty ($arrRequests) )
                                            {
                                                foreach ($arrRequests as $objRequest) {

                                                    if ( $objRequest->getId () === (int) $objRequest->getId () )
                                                    {
                                                        $blHasRequest = true;
                                                    }
                                                }
                                            }

                                            $displayCancel = $blHasRequest === true ? 'block' : 'none';
                                            $showRequest = $blHasRequest === false ? 'block' : 'none';
                                            $image = trim ($arrPage->getFileLocation ()) !== "" && file_exists ($rootPath . $arrPage->getFileLocation ()) ? $arrPage->getFileLocation () : '/blab/public/img/avatar.gif';
                                            ?>

                                            <div class="vpb_groups_box notMember">
                                                <div class="col-lg-2 pull-left" style="padding:10px;">
                                                    <a href="/blab/page/index/<?= $arrPage->getUrl () ?>">
                                                        <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                                    <div class="vproducttitle">
                                                        <a href="/blab/page/index/<?= $arrPage->getUrl () ?>">
                                                            <span><?= $arrPage->getName () ?></span>
                                                        </a>
                                                    </div>
                                                    <div class="vproductprice">
                                                        <div class="vpull_left"><?= $arrPage->getFollowCount () ?> members</div>
                                                        <div class="vpull_left"><?= $arrPage->getLikeCount () ?> likes</div>



                                                        <div class="vpull_right">
                                                            <?php
                                                            if ( $blHasRequest === true )
                                                            {
                                                                echo '<span style="margin-top:12px;" class="label label-primary">Following</span>';
                                                            }
                                                            ?>
                                                        </div>

                                                        <div style="clear:both;"></div>
                                                    </div>
                                                </div>
                                            </div>

                                        <?php } ?>

                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>


        </div>
    </div>


</div>

<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/geocomplete.js"></script>

<script>

                                $ ("#pageCategory").on ("change", function ()
                                {
                                    vpb_load_more_pages (true);
                                });

                                function search ()
                                {

                                    if ($.trim ($ ("#searchText")).val () === "")
                                    {
                                        return false;
                                    }

                                    vpb_load_more_pages (true);
                                }

</script>