<?php

if ( !empty ($arrUsers) )
{

    echo '<div class="full-height-scroll" style="overflow: auto; width: auto; height: 400px;">

                                        <strong>Likes</strong>

                                        <ul class="list-group clear-list">';

    foreach ($arrUsers as $arrUser) {
        echo '<li class="list-group-item fist-item">';


        echo '<img style="width:50px;" src="/blab/public/uploads/profile/' . $arrUser->getUsername () . '.jpg">';

        echo $arrUser->getFirstName () . ' ' . $arrUser->getLastName ();


        echo '</li>';
    }

    echo '</div>';
    echo '</ul>';
}