<?php

echo '<div class="full-height-scroll" style="overflow: auto; width: auto; height: 400px; margin-top: 20px;
    float: left;
    width: 100%;
    margin-left:16px;
}">';

echo '<div class="col-lg-12 pull-left" style="margin-bottom:16px;">';
echo '<button id="createEvent" type="button" class="btn btn-w-m btn-primary">Create Event</button>';
echo '</div>';


if ( !empty ($arrEvents) )
{

    foreach ($arrEvents as $arrEvent) {
        echo '<div class="col-lg-2" style="border: 1px solid #CCC; height:200px; padding:10px;">';


        echo '<a href="#">' . $arrEvent->getEventName () . '</a>';
        echo '<br/><small>' . $arrEvent->getEventDate () . '<small>';


        echo '</div>';
    }

    echo '</div>';
}