<?php
$totalCommentsToDisplay = 1;

function getTextColour ($memberEventStatus, $status)
{
    if ( (int) $memberEventStatus === (int) $status )
    {
        $color = "#1ab394";
    }
    else
    {
        $color = "#676a6c";
    }

    return $color;
}

$friendIds = [];

foreach ($arrFriendList as $friend) {
    $friendIds[] = $friend->getId ();
}

$permission = true;

if ( !in_array ($_SESSION['user']['user_id'], $arrMemberIds) && strtolower (trim ($eventType)) === "private" )
{
    echo '<h2>This is a closed event</h2>';
    exit;
}
?>

<input type="hidden" id="currentEventId" name="currentEventId" value="<?= $objEvent->getId () ?>">

<div class="row">
    <div class="col-lg-12">
        <div class="col-lg-3">
            <?php
            $this->partial ("templates/events", ["arrEvents" => $arrEvents]);

            $this->partial ("templates/profileUpload", ["arrUser" => $objUser, "friendIds" => $friendIds]);

            $this->partial (
                    "templates/friends", [
                "arrFriendList" => $arrFriendList,
                    ]
            );
            ?>
        </div>

        <div class="col-lg-6">
            <div class="row">
                <div class="ibox">
                    <div class="ibox-content">
                        <div class="text-center m-t-md">
                            <h2><?= $objEvent->getEventName () ?></h2>
                            <!-- timeline profile picture -->
                            <a href="#" id="timelineProfilePic">
                                <img class="currentImage" src="<?= $objEvent->getImageLocation () ?>">
                                <br>Click to upload

                            </a>

                            <div style="display:none;">
                                <form id="groupImage" method="post" enctype="multipart/form-data">
                                    <div class="uploadFile2">
                                        <input type="file" class="custom-file-upload" name="userImage" id="profileimgaa">
                                    </div>
                                </form>
                            </div>

                            <div class="uploadedImage">

                            </div>

                        </div>
                    </div>

                    <div id="group_page_menu" class="group_manin_menu_wrapper">
                        <div id="not_deleting_group" style="width:100%; display:block;">
                            <div style="clear:both;"></div>
                            <span id="g_discussion" class="group_menu_wrapper_active" onclick="vpb_show_status_updates ();">Discussion</span>
                            <span id="g_members" class="group_menu_wrapper" onclick="<?= ($permission === true ? 'vpb_show_event_page_members ();' : '') ?>">Members</span>
                            <span class="group_menu_wrapper" onclick="<?= ($permission === true ? 'vpb_load_event_photos(\'' . $objEvent->getEventName () . '\');' : '') ?>">Photos</span>

                            <span id="g_videos" class="group_menu_wrapper" onclick="<?= ($permission === true ? 'vpb_show_event_videos();' : '') ?>">Videos</span>

                            <span id="g_videos" class="group_menu_wrapper" onclick="vpb_shoq_report_this_event_box ('Michael hampton', 'michaelhampton', 'bluetiger_uan@yahoo.com', '<?= $objEvent->getId () ?>', '<?= $objEvent->getEventName () ?>')">Report Group</span>             
                            <span id="vpb_get_all_the_group_confirmation_box" class="group_menu_wrapper"></span> 

                            <?php if ( $objEvent->getUserId () === $_SESSION['user']['user_id'] ): ?> 
                                <span onclick="vpb_confirm_delete_current_event_details ('<?= $objEvent->getId () ?>', 'michaelhampton', '<?= $objEvent->getEventName () ?>');
                                      " style="float:right!important;
                                      " class="group_menu_wrapper vasplus_tooltip_icons" original-title="Delete this Group"><i class="fa fa-remove v_edit_group_details"></i></span>
                                <span onclick="vpb_set_current_event_details (<?= $objEvent->getId () ?>);" style="float:right !important;border-left: 1px solid #e5e5e5;" class="group_menu_wrapper vasplus_tooltip_icons" original-title="Edit Group Details"><i class="fa fa-pencil-square v_edit_group_details"></i></span>
                            <?php endif; ?>

                        </div>
                        <div style="clear:both;"></div>


                    </div>
                </div>



                <div class="row event-details" style="margin-bottom: 12px;">
                    <div class="col-md-3">
                        <button type="button" status="1" class="btn btn-primary btn-sm btn-block eventResponse"><i class="fa fa-envelope"></i> Going
                        </button>
                    </div>
                    <div class="col-md-3">
                        <button type="button" status="2" class="btn btn-danger btn-sm btn-block eventResponse"><i class="fa fa-coffee"></i> Not Going
                        </button>
                    </div>
                    <div class="col-md-3">
                        <button type="button" status="3" class="btn btn-success btn-sm btn-block eventResponse"><i class="fa fa-coffee"></i> Interested
                        </button>
                    </div>
                </div>

                <div class="ibox event-details">
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-lg-12" style="width:100%;">

                                <div class="col-lg-12 pull-left" style="width:100%; border-bottom: 1px solid #CCC;">
                                    <dl class="dl-horizontal">

                                        <dt>Location:</dt>
                                        <dd><?= $objEvent->getLocation () ?></dd>
                                        <dt>Event Date:</dt>
                                        <dd> <?= $objEvent->getEventDate () ?></dd>
                                        <dt>Event Time:</dt>
                                        <dd><?= $objEvent->getEventTime () ?></dd>
                                    </dl>
                                </div>

                                <div class="col-md-12">
                                    <div class="col-md-3">
                                        <h5 class="getStatusList" status="1"><strong class="going"><h2><?= $objEvent->getGoingCount () ?></h2></strong> <span style="color: <?= getTextColour ($memberEventStatus, 1) ?>">Going</span></h5>
                                    </div>

                                    <div class="col-md-3">
                                        <h5 class="getStatusList" status="2"><strong class="not_going"><h2><?= $objEvent->getNotGoingCount () ?></h2></strong> <span style="color: <?= getTextColour ($memberEventStatus, 2) ?>">Not Going</span></h5>

                                    </div>

                                    <div class="col-md-3">
                                        <h5 class="getStatusList" status="3"><strong class="interested"><h2><?= $objEvent->getInterestedCount () ?></h2></strong> <span style="color: <?= getTextColour ($memberEventStatus, 3) ?>">Interested</span></h5>

                                    </div>

                                    <div class="col-md-3">
                                        <h5 class="getStatusList" status="4"><strong class="interested"><h2><?= $objEvent->getPendingCount () ?></h2></strong> <span style="color: <?= getTextColour ($memberEventStatus, 4) ?>">Pending</span></h5>

                                    </div>

                                </div>

                                <?php
                                if ( (int) $objEvent->getUserId () === (int) $_SESSION['user']['user_id'] )
                                {
                                    ?>

                                    <div class="col-lg-12">
                                        <button event-id="<?= $objEvent->getId () ?>" type="button" class="btn btn-w-m btn-primary pull-left invitationWindow">Invite Friends</button>
                                    </div>

                                <?php } ?>
                            </div>

                        </div>
                    </div>
                </div>

                <div id="vasplus_wall_status_updates" style="width:100%;">
                    <?php
                    if ( in_array ($_SESSION['user']['user_id'], $arrMemberIds) )
                    {
                        $this->partial ("templates/postBox", ["form" => "eventcommentform"]);

                        echo ' <div class="row"></div>';


                        echo '<div id="posts-list" style="margin-top: 20px;">';
                        $this->partial (
                                "templates/posts", [
                            "arrPosts" => $arrPosts,
                            "totalCommentsToDisplay" => $totalCommentsToDisplay
                                ]
                        );
                        echo '</div>';
                    }
                    ?>

                </div>

                <span id="deleting_group"></span>

                <div class="vmiddle_other" id="vasplus_group_page_members">
                    <div class="vmiddle_other_title vprofile_o_title">
                        <div style="float:left;">Members · <span class="vtotals"><?= count ($arrMembers) ?></span></div>
                        <div style="float:right; font-weight:normal !important; font-size:13px !important;">
                            <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" title="Close" onClick="vpb_show_status_updates ();">×</button>
                        </div>
                        <div style="clear:both;"></div>
                    </div>

                    <div id="vpb_get_all_the_groups_members">

                        <div style="margin-left:4px;margin-right:4px;margin-bottom:4px !important;position:relative;" align="center">   

                            <?php
                            foreach ($arrMembers as $arrGroupMember) {

                                $status = $arrGroupMember->getIsActive ();

                                switch ($status) {
                                    case 1:
                                        $label = 'Going';
                                        break;
                                    case 2:
                                        $label = 'Not Going';
                                        break;
                                    case 3:
                                        $label = 'Interested';
                                        break;
                                    case 4:
                                        $label = 'Pending';
                                        break;
                                }

                                echo '<div class="vfriendsPhotos_wraper">
                <a href="/blab/index/profile/' . $arrGroupMember->getUsername () . '">
                    
                <img src="/blab/public/uploads/profile/' . $arrGroupMember->getUsername () . '.jpg" border="0">
                     ' . $label . '
                <span>' . $arrGroupMember->getFirstname () . ' ' . $arrGroupMember->getLastname () . '</span>
                </a> 
               
                 </div>';
                            }
                            ?>

                        </div>

                    </div>
                </div>

                <!-- Display this Page Group Members Ends -->


                <!-- Display this Page Group Videos Starts -->
                <div class="vmiddle_other" id="vasplus_group_page_videos">
                    <div class="vmiddle_other_title vprofile_o_title">
                        <div style="float:left;">Videos · <span class="vtotals">0</span></div>
                        <div style="float:right; font-weight:normal !important; font-size:13px !important;">
                            <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" title="Close" onClick="vpb_show_status_updates ();">×</button>
                        </div>
                        <div style="clear:both;"></div>
                    </div>

                    <div id="vpb_get_all_the_groups_videos"><div style="padding:10px;" title="Loading..." class="btn_loading">Loading<span class="dots"><span>.</span><span>.</span><span>.</span></span></div></div>
                </div>

                <!-- Display this Page Group Photos Starts -->
                <div class="vmiddle_other" id="vasplus_group_page_photos">
                    <div class="vmiddle_other_title vprofile_o_title">
                        <div style="float:left;">Photos · <span class="vtotals"><?= count ($arrPhotos) ?></span></div>
                        <div style="float:right; font-weight:normal !important; font-size:13px !important;">
                            <button type="button" class="close vasplus_tooltip_photo_e" style="margin:0px !important;" title="Close" onClick="vpb_show_status_updates ();">×</button>
                        </div>
                        <div style="clear:both;"></div>
                    </div>

                    <div id="vpb_get_all_the_groups_photos">
                        <div class="lightBoxGallery">
                            <?php
                            if ( !empty ($arrPhotos) )
                            {
                                foreach ($arrPhotos as $key => $arrPhoto) {

                                    if ( $key === 0 )
                                    {
                                        $id = $arrPhoto->getId ();
                                    }

                                    echo '<input type="hidden" id="hidden_photo_link_' . $id . '_' . ($key + 1) . '" value="' . $arrPhoto->getFileLocation () . '">';

                                    echo '<a href="#"  onclick="vpb_popup_photo_box(\'' . $arrPhoto->getId () . '\', \'' . count ($arrPhotos) . '\', \'' . ($key + 1) . '\', \'' . $arrPhoto->getFileLocation () . '\');" title="Image from Unsplash" data-gallery=""><img src="' . $arrPhoto->getFileLocation () . '"></a>';
                                }
                            }
                            else
                            {
                                echo '<h2>The group currently has no photos</h2>';
                            }
                            ?>

                        </div>
                    </div>
                </div>
            </div>


        </div>

        <div class="col-lg-3 l-sidebar">
            <div id="vpb_get_all_the_users_groups">

            </div>
            <br clear="all">
        </div>
    </div>
</div>



<script>

    var groupId = <?= $objEvent->getId () ?>;
    var groupName = '<?= $objEvent->getEventName () ?>';
    var memberEventStatus = '<?= $memberEventStatus ?>';

    var selectedImageType = "event";
    var selectedImageId = groupId;

</script>

<script src="/blab/public/js/geocomplete.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA1COtE7cJxfGxNWiTjEgtSNhbvDBCiiqQ&libraries=places"></script>
<script src="/blab/public/js/geocomplete.js"></script>
<script src="/blab/public/js/newsFeed.js"></script>
<script src="/blab/public/js/event.js" type="text/javascript"></script>

