<?php
$totalCommentsToDisplay = 1;

$friendIds = [];

foreach ($arrFriendList as $friend) {
    $friendIds[] = $friend->getId ();
}

$requestIds = [];

foreach ($arrFriendRequests as $objFriendRequest) {
    $requestIds[] = $objFriendRequest->getId ();
}
?>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="row">
                <?php
                $this->partial ("templates/profileUpload", ["arrUser" => $objUser, "friendIds" => $friendIds, "requestIds" => $requestIds]);
                $this->partial ("templates/links");
                ?>
            </div>

        </div>

        <div class="col-md-9">
            <!-- Display Group Details -->

            <div class="vprofile_o_detail" style="border-bottom:0px solid !important;">
                <div class="vprofile_o_title" style="padding:0px;">
                    <div style="float:left; padding:10px;">
                        Events            
                    </div>
                    <div style="float:right; padding:10px;">
                        <span class="create_btn" onclick="vpb_reset_current_group_details ();"><i class="fa fa-plus" style="font-weight:normal !important;"></i> Create Event</span>

                    </div><div style="clear:both;"></div></div>
                <div style="clear:both;"></div>
            </div>

            <div style="clear:both;"></div>

            <div style="width:100%; margin:0 auto; text-align:center; display:table;" align="center">
                <input type="hidden" id="vtotal_groups" value="<?= $totalCount ?>">
                <input type="hidden" id="vpb_groups_start" value="<?= $paginationLimit ?>">
                <input type="hidden" id="vpb_total_groups_per_load" value="<?= $paginationLimit ?>">

                <div class="input-group vpb-the-friends-wrap" id="vpb_load_more_group_box">

                    <div style="float:left;"><span class="vpb_hover" style="color:#3b5998;" onclick="vpb_load_more_events ();">View more events</span></div>
                    <div style="float:right; color:#999;"><span id="v_this_members_totals"><?= count ($arrEvents) ?></span> of <?= $totalCount ?></div>
                    <div style="clear:both;"></div>
                </div>

                <!-- Loading Gif -->
                <div class="input-group vpb-the-friends-wrap" style="display:none;padding:7px 10px !important;" id="vpb_loading_group_members_outer">
                    <div id="vpb_loading_group_members"></div>
                </div>

                <div class="col-md-12" style="padding:0px !important;">
                    <div class="input-group">
                        <input onkeyup="vpb_load_more_events (true)" id="searchText" type="text" placeholder="Search" class="input-sm form-control"> 
                        <span class="input-group-btn">
                            <button onclick="vpb_load_more_events (true)" type="button" class="btn btn-sm btn-primary"> Go!</button> 
                        </span>
                    </div>
                </div>

                <div id="vpb_loaded_group_members" style=" width:100%;">
                    <?php
                    foreach ($arrEvents as $arrEvent) {
                        $image = trim ($arrEvent->getImageLocation ()) !== "" && file_exists ($rootPath . $arrEvent->getImageLocation ()) ? $arrEvent->getImageLocation () : '/blab/public/img/avatar.gif';
                        ?>

                        <div class="vpb_groups_box">
                            <div class="col-lg-2 pull-left" style="padding:10px;">
                                <a href="/blab/event/index/<?= $arrEvent->getId () ?>">
                                    <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                <div class="vproducttitle"><a href=""/blab/event/index/<?= $arrEvent->getId () ?>"><span><?= $arrEvent->getEventName () ?></span></a></div>


                            </div>
                        </div>

                    <?php } ?>

                </div>
                <div style="clear:both;"></div>
            </div>


        </div>
    </div>


</div>

<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/geocomplete.js"></script>