<?php
$totalCommentsToDisplay = 1;

$friendIds = [];

foreach ($arrFriendList as $friend) {
    $friendIds[] = $friend->getId ();
}

$requestIds = [];

foreach ($arrFriendRequests as $objFriendRequest) {
    $requestIds[] = $objFriendRequest->getId ();
}
?>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="row">
                <?php
                $this->partial ("templates/profileUpload", ["arrUser" => $objUser, "friendIds" => $friendIds, "requestIds" => $requestIds]);
                $this->partial ("templates/links");
                ?>
            </div>

        </div>

        <div class="col-md-9">
            <!-- Display Group Details -->

            <div class="vprofile_o_detail" style="border-bottom:0px solid !important;">
                <div class="vprofile_o_title" style="padding:0px;">
                    <div style="float:left; padding:10px;">
                        Events            
                    </div>
                    <div style="float:right; padding:10px;">
                        <span class="create_btn" id="createEvent"><i class="fa fa-plus" style="font-weight:normal !important;"></i> Create Event</span>

                    </div><div style="clear:both;"></div></div>
                <div style="clear:both;"></div>
            </div>

            <div style="clear:both;"></div>

            <div style="width:100%; margin:0 auto; text-align:center; display:table;" align="center">
                <input type="hidden" id="vtotal_groups" value="<?= $totalCount ?>">
                <input type="hidden" id="vpb_groups_start" value="<?= $paginationLimit ?>">
                <input type="hidden" id="vpb_total_groups_per_load" value="<?= $paginationLimit ?>">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="wrapper wrapper-content animated fadeInUp">

                            <div class="ibox col-lg-12">
                                <div class="ibox-title">
                                    <h5>Events you are invited to</h5>

                                </div>
                                <div class="ibox-content col-lg-12 pull-left" style="width: 100%;">
                                    <?php
                                    foreach ($arrMemberEvents as $arrMemberEvent) {
                                        $image = trim ($arrMemberEvent->getImageLocation ()) !== "" && file_exists ($rootPath . $arrMemberEvent->getImageLocation ()) ? $arrMemberEvent->getImageLocation () : '/blab/public/img/avatar.gif';
                                        ?>

                                        <div class="vpb_groups_box member col-lg-12">
                                            <div class="col-lg-2 pull-left" style="padding:10px;">
                                                <a href="/blab/event/index/<?= $arrMemberEvent->getId () ?>">
                                                    <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                                <div class="vproducttitle">
                                                    <a href="/blab/event/index/<?= $arrMemberEvent->getId () ?>">
                                                        <span><?= $arrMemberEvent->getEventName () ?></span>
                                                    </a>
                                                </div>
                                                <div class="vproductprice">
                                                    <div class="vpull_left">
                                                        <span style="margin:2px; float: left;" class="label label-primary"><?= $arrMemberEvent->getGoingCount () ?> Going</span> <br>
                                                        <span style="margin:2px; float: left;" class="label label-danger"><?= $arrMemberEvent->getNotGoingCount () ?>Not Going</span> <br>
                                                        <span style="margin:2px; float: left;" class="label label-success"><?= $arrMemberEvent->getInterestedCount () ?>Interested</span> <br>
                                                        <span style="margin:2px; float: left;" class="label label-warning"><?= $arrMemberEvent->getPendingCount () ?>Pending</span> <br>

                                                    </div>

                                                    <div style="clear:both;"></div>
                                                </div>
                                            </div>
                                        </div>

                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div style="margin-top:10px; margin-bottom:10px;;" class="input-group vpb-the-friends-wrap" id="vpb_load_more_group_box">

                    <div style="float:left;"><span class="vpb_hover" style="color:#3b5998;" onclick="vpb_load_more_events ();">View more events</span></div>
                    <div style="float:right; color:#999;"><span id="v_this_members_totals"><?= count ($arrEvents) ?></span> of <?= $totalCount ?></div>
                    <div style="clear:both;"></div>
                </div>

                <!-- Loading Gif -->
                <div class="input-group vpb-the-friends-wrap" style="display:none;padding:7px 10px !important;" id="vpb_loading_group_members_outer">
                    <div id="vpb_loading_group_members"></div>
                </div>

                <div class="col-lg-12" style="float: left; background-color: #FFF; padding: 10px; border: 1px solid #CCC; margin-top:8px; margin-bottom: 8px; border-radius: 5px;">

                    <input type="hidden" id="pageCategory" name="pageCategory">

                    <ul class="tag-list" style="padding: 0; width: 100%;">
                        <?php
                        foreach ($arrCategories as $arrCategory) {
                            echo '<li id="' . $arrCategory->getId () . '"><a href=""><i class="fa fa-tag"></i> ' . $arrCategory->getName () . '</a></li>';
                        }
                        ?>
                    </ul>
                </div>

                <div class="col-md-12" style="padding:0px !important;">
                    <div class="input-group">

                        <input style="width: 100%;" onkeyup="vpb_load_more_events (true)" id="searchText" type="text" placeholder="Search" class="input-sm form-control"> 
                        <span class="input-group-btn">
                            <button onclick="search ()" type="button" class="btn btn-sm btn-primary"> Go!</button> 
                        </span>
                    </div>
                </div>


                <div class="ibox col-lg-12">
                    <div class="ibox-title">
                        <h5>All events</h5>

                    </div>
                    <div class="ibox-content col-lg-12 pull-left" style="width:100%;">
                        <div id="vpb_loaded_group_members" style=" width:100%;">
                            <?php
                            foreach ($arrEvents as $arrEvent) {
                                $image = trim ($arrEvent->getImageLocation ()) !== "" && file_exists ($rootPath . $arrEvent->getImageLocation ()) ? $arrEvent->getImageLocation () : '/blab/public/img/avatar.gif';
                                ?>

                                <div class="vpb_groups_box">
                                    <div class="col-lg-2 pull-left" style="padding:10px;">
                                        <a href="/blab/event/index/<?= $arrEvent->getId () ?>">
                                            <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                        <div class="vproducttitle"><a href="/blab/event/index/<?= $arrEvent->getId () ?>"><span><?= $arrEvent->getEventName () ?></span></a></div>

                                        <div class="vproductprice">
                                            <div class="vpull_left">
                                                <span style="margin-top:2px; float: left;" class="label label-primary"><?= $arrEvent->getGoingCount () ?> Going</span> <br>
                                                <span style="margin-top:2px; float: left;" class="label label-danger"><?= $arrEvent->getNotGoingCount () ?>Not Going</span> <br>
                                                <span style="margin-top:2px; float: left;" class="label label-success"><?= $arrEvent->getInterestedCount () ?>Interested</span> <br>
                                                <span style="margin-top:2px; float: left;" class="label label-warning"><?= $arrEvent->getPendingCount () ?>Pending</span> <br>

                                            </div>

                                            <div style="clear:both;"></div>
                                        </div>

                                    </div>
                                </div>

                            <?php } ?>
                        </div></div>

                </div>
                <div style="clear:both;"></div>
            </div>


        </div>
    </div>


</div>

<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/geocomplete.js"></script>

<script>

                                $ (".tag-list > li").on ("click", function ()
                                {
                                    var categoryId = $ (this).attr ("id");

                                    if (!categoryId)
                                    {
                                        showErrorMessage ('Invalid category id');
                                        return false;
                                    }

                                    $ ("#pageCategory").val (categoryId);
                                    vpb_load_more_events (true);

                                    return false;

                                });
                                
                                function search ()
                                {

                                    if ($.trim ($ ("#searchText")).val () === "")
                                    {
                                        return false;
                                    }

                                    vpb_load_more_events (true);
                                }

</script>