<style>

    .round {
        position: relative;
    }

    .round label {
        background-color: #fff;
        border: 1px solid #ccc;
        border-radius: 50%;
        cursor: pointer;
        height: 28px;
        left: 0;
        position: absolute;
        top: 0;
        width: 28px;
    }

    .round label:after {
        border: 2px solid #fff;
        border-top: none;
        border-right: none;
        content: "";
        height: 6px;
        left: 7px;
        opacity: 0;
        position: absolute;
        top: 8px;
        transform: rotate(-45deg);
        width: 12px;
    }

    .round input[type="checkbox"] {
        visibility: hidden;
    }

    .round input[type="checkbox"]:checked + label {
        background-color: #66bb6a;
        border-color: #66bb6a;
    }

    .round input[type="checkbox"]:checked + label:after {
        opacity: 1;
    }
</style>

<div class="full-height-scroll" style="">

    <strong>Members</strong>

    <ul class="list-group clear-list" style="min-height: 150px !important;">
        <?php foreach ($arrMembers as $key => $arrMember) { ?>

            <li class="list-group-item fist-item pull-left col-lg-12" style="border-bottom: 1px dotted #CCC; min-height: 50px;">

                <div class="col-lg-8 pull-left">
                    <span class="pull-left"><img class="img-responsive" style="max-width: 50px;" src="/blab/public/uploads/profile/<?= $arrMember->getUsername () ?>.jpg"> </span>

                    <?= $arrMember->getFirstName () . ' ' . $arrMember->getLastName (); ?>
                </div>

                <div class="col-lg-4 pull-left">
                    <div class="round">
                        <input class="inviteCheckbox" type="checkbox" value="<?= $arrMember->getId () ?> " id="checkbox<?= $key ?>" />
                        <label for="checkbox<?= $key ?>"></label>
                    </div>
                </div>
            </li>

        <?php } ?>

    </ul>

</div>

<div class="modal-footer" style="border: none !important">
    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary SaveInvited">Save changes</button>
</div>

<script>
    $ (".SaveInvited").on ("click", function ()
    {
        var searchIDs = $ ('.inviteCheckbox:checked').map (function ()
        {

            return $ (this).val ();

        });

        var userIds = searchIDs.get ();

        var eventId = $ ("#currentEventId").val ();

        if (!eventId)
        {
            showErrorMessage ();
            return false;
        }


        var dataString = {"eventId": eventId, "userIds": userIds};

        $.post ('/blab/event/saveInvitations', dataString, function (response)
        {
            try {
                var objResponse = $.parseJSON (response);

                if (objResponse.sucess == 0)
                {
                    showErrorMessage (objResponse.message);
                    return false;
                }
                else
                {
                    showSuccessMessage ('Requests have been sent for your friends to jon the group');
                }

            } catch (error) {
                showErrorMessage ();
            }


        }).fail (function (error_response)
        {
            showErrorMessage ();
        });
    });
</script>