<style>
    .datepicker {
        z-index: 999999999 !important;
    }
</style>
<div class="modal-dialog">
    <div class="modal-content animated flipInY">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Update Event</h5>

            </div>
            <div class="ibox-content">
                <form class="form-horizontal" name="eventForm" id="eventForm">
                    
                    <input type="hidden" id="eventId" name="eventId" value="<?= $objEvent->getId() ?>">
                    
                    <div class="form-group">
                        <label class="col-lg-2 control-label">Event Name</label>

                        <div class="col-lg-10">
                            <input type="text" placeholder="Event Name" id="eventName" name="eventName" class="form-control" value="<?= $objEvent->getEventName () ?>"> 
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label">Location</label>

                        <div class="col-lg-10">
                            <input id="geocomplete" type="text" placeholder="Type in an address" value="<?= $objEvent->getLocation () ?>" />
                            <input style="display:none;" id="find" type="button" value="find" />
    <!--                                <input type="text" placeholder="Location" id="geocomplete" name="location" class="form-control"></div>-->
                        </div>
                    </div>

                    <div class="geo-details">

                    </div>



                    <div class="form-group">
                        <label class="col-lg-2 control-label">Event Date</label>

                        <div class="col-lg-10">
                            <input type="text" placeholder="Event Date" id="eventDate" name="eventDate" class="form-control" value="<?= $objEvent->getEventDate () ?>"></div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label">Event Time</label>

                        <div class="input-group clockpicker col-lg-10" data-autoclose="true">
                            <input type="text" class="form-control" value="<?= $objEvent->getEventTime () ?>" >
                            <span class="input-group-addon">
                                <span class="fa fa-clock-o"></span>
                            </span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label">Event Type</label>

                        <?php $arrEventTypes = array("public" => "Public", "private" => "Private"); ?>

                        <div class="col-lg-10">
                            <select id="eventType" name="eventType" class="form-control">
                                <?php
                                foreach ($arrEventTypes as $key => $value) {
                                    $selected = trim ($key) === trim ($objEvent->getEventType ()) ? 'selected="selected"' : '';
                                    echo '<option value="' . $key . '" ' . $selected . '>' . $value . '</option>';
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 control-label">Event Category</label>

                        <div class="col-lg-10">
                            <select id="eventCategory" name="eventCategory" class="form-control">
                                <?php
                                foreach ($arrCategories as $arrCategory) {
                                    $selected = (int) trim ($objEvent->getEventCategory ()) === (int) $arrCategory->getId () ? 'selected="selected"' : '';

                                    echo '<option value="' . $arrCategory->getId () . '" ' . $selected . '>' . $arrCategory->getName () . '</option>';
                                }
                                ?>
                            </select>
                        </div>
                    </div>

                    <div style="height: 250px; overflow-y: auto; width: 100%;">
                        <ul class="list-group clear-list" style="width:100%">

                            <?php //foreach ($arrFriendList as $friend): ?>
<!--
                                <li class="list-group-item fist-item" style="width:100%;">
                                    <?//= $friend->getFirstName () . ' ' . $friend->getLastName () ?>
                                    <input class="checkbox-primary event-checkbox" type="checkbox" value="<?//= $friend->getId () ?>">
                                </li>-->

                            <?php //endforeach; ?>
                        </ul>

                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button class="btn btn-sm btn-primary saveEvent" type="submit">Save</button>
                            <button type="button" class="btn btn-white" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>

    $ ('#eventDate').datepicker ({
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        calendarWeeks: true,
        autoclose: true
    });

    $ ("#geocomplete").on ("keyup", function ()
    {

        var locationTyped = $ (this).val ();

        if (locationTyped.length > 0)
        {
            $ (".geo-details").html ('');

            $ (".geo-details").html ('<div class="dropdown"><ul class="dropdown-menu vpb-hundred-percent_loading" style="top:auto;"><li class="dropdown-header vpb_wall_loading_text">' + $ ("#v_loading_btn").val () + '</li></ul></div>');


            var dataString = {'location': locationTyped};

            $.post ('/blab/index/locationSearch/true', dataString, function (response)
            {

                if (response == "")
                {
                    $ (".geo-details").html ('');
                }
                else
                {
                    $ (".geo-details").html ('<div class="dropdown"><ul class="dropdown-menu vpb-hundred-percent v_overflow_this_field" id="location_suggestion_box" style="top:auto;">' + response + '</ul></div>');
                }


            }).fail (function (error_response)
            {
                setTimeout ("buildLocationResults('" + locationTyped + "');", 10000);
            });
        }
        else
        {
            $ (".geo-details").html ('');
            return false;
        }
    });

    function buildLocationResults (location)
    {
        $ ("#geocomplete").val (location);
        $ (".geo-details").html ("");

    }

    $ ('.clockpicker').clockpicker ();

    $ (".saveEvent").off ();
    $ (".saveEvent").on ("click", function ()
    {
        var groupIds = $ (".event-checkbox:checked").map (function ()
        {
            return $ (this).val ();
        }).get ();

        var arrData = {
            eventName: $ ("#eventName").val (),
            eventId: $("#eventId").val(),
            eventCategory: $ ("#eventCategory").val (),
            eventType: $ ("#eventType").val (),
            location: $ ("#geocomplete").val (),
            eventDate: $ ("#eventDate").val (),
            eventTime: $ ('.clockpicker > input').val (),
        };

        $.ajax ({
            url: '/blab/event/updateEvent',
            type: 'POST',
            data: arrData,
            success: function (response)
            {
                formatResponse (response, 'The event was created successfully.');
            }
        });


        return false;
    });
</script>