<div class="client-detail">

    <input type="text" class="form-control" id="emailAddress" name="emailAddress">
    <input type="hidden" id="messageId" name="messageId" value="<?= $messageId ?>">

    <strong>Select Friend</strong>

    <ul class="list-group clear-list">
        <?php
        if ( !empty ($arrFriends) )
        {
            foreach ($arrFriends as $arrFriend) {
                echo ' <li class="list-group-item fist-item">
                                                <span class="pull-right"><a userId="' . $arrFriend->getId () . '"href="#" class="btn btn-sm btn-success sendMessageForward"> Send </a></span>
                                               ' . $arrFriend->getFirstname () . ' ' . $arrFriend->getLastname () . ' 
                                            </li>';
            }
        }
        else
        {
            echo '<h2>You have no friends to send this to </h2>';
        }
        ?>

    </ul>
</div>

<script>
    $ (".sendMessageForward").on ("click", function ()
    {
        var messageId = $ ("#messageId").val ();
        var userId = $ (this).attr ("userId");
        $ (this).text ("Sending");

        if (!messageId)
        {
            alert ("Invalid messaage id");
            return false;
        }

        if (!userId)
        {
            alert ("Invalid user id");
            return false;
        }

        var element = $ (this);

        $.ajax ({
            type: "POST",
            url: '/blab/chat/sendMessageForward/',
            data: {"messageId": messageId, "userId": userId},
            cache: false,
            beforeSend: function ()
            {
            },
            success: function (response)
            {
                try {
                    var objResponse = $.parseJSON (response);

                    if (objResponse.sucess == 0)
                    {
                        if (objResponse.message !== undefined)
                        {
                            showErrorMessage (objResponse.message);
                        }
                    }
                    else
                    {
                        showSuccessMessage ('The message has been forwarded successfully');
                        element.text ("Sent");

                    }

                } catch (error) {
                    showErrorMessage ('Ajax request failed enuexpectedly');
                }
            }
        }).fail (function (error_response)
        {
            showErrorMessage ('Ajax request failed enuexpectedly');
        });

        return false;
    });
</script>



