<link href="/blab/public/css/newsFeed.css" rel="stylesheet" type="text/css">
<link href="/blab/public/css/chat.css" rel="stylesheet" type="text/css">

<div class="row">
    <div class="col-lg-4 pull-left">
        <div class="ibox">
            <div class="ibox-content" style="padding: 10px;">
                <h2>Chat</h2>

                <div class="input-group">
                    <input type="text" placeholder="Search Users " id="chatUserSearchBox" class="input form-control pull-left">

                </div>

                <ul class="category-list" style="padding: 0">
                    <?php
                    echo '<h5>Friends</h5>';

                    foreach ($arrUsers as $arrUser):

                        $onlineLabel = 'text-danger';

                        if ( trim ($arrUser->getLastLogin ()) !== "" )
                        {
                            $dbdate = strtotime ($arrUser->getLastLogin ());
                            if ( time () - $dbdate <= 15 * 60 )
                            {
                                $onlineLabel = 'text-navy';
                            }
                            else
                            {
                                $onlineLabel = 'text-danger';
                            }
                        }
                        else
                        {
                            $onlineLabel = 'text-danger';
                        }


                        if ( $arrUser->getId () !== $_SESSION['user']['user_id'] ):
                            ?>
                            <li><a class="show-chat single" groupname="" groupid="" username="<?= $arrUser->getUsername () ?>" fullname="<?= $arrUser->getFirstName () . '|' . $arrUser->getLastName () ?>" session-user="<?= $_SESSION['user']['username'] ?>" user-id="<?= $arrUser->getId () ?>" href="#"> <i class="fa fa-circle <?= $onlineLabel ?>"></i> <?= $arrUser->getFirstName () . ' ' . $arrUser->getLastName () ?> </a></li>

                            <?php
                        endif;
                    endforeach;

                    if ( isset ($arrChatGroups) && !empty ($arrChatGroups) ):

                        echo '<h5>Groups</h5>';

                        foreach ($arrChatGroups as $arrChatGroup):
                            ?>
                            <li><a class="show-chat group" groupname="<?= $arrChatGroup['name'] ?>" groupid="<?= $arrChatGroup['group_id'] ?>" username="<?= $arrChatGroup['users'] ?>" fullname="<?= $arrChatGroup['fullname'] ?>" session-user="<?= $_SESSION['user']['username'] ?>" href="#"> <i class="fa fa-circle text-danger"></i> <?= $arrChatGroup['name'] ?> </a></li>

                            <?php
                        endforeach;
                    endif;
                    ?>

                </ul>
            </div>
        </div>
    </div>

    <div class="col-lg-8 chatWindow pull-left">

    </div>
</div>



<script src="/blab/public/js/geocomplete.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA1COtE7cJxfGxNWiTjEgtSNhbvDBCiiqQ&libraries=places"></script>
<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/chat.js" type="text/javascript"></script>

<script>
<?php
if ( !empty ($_GET['username']) )
{
    ?>
        var username = '<?= $_GET['username']; ?>';
        $ (".single[username='" + username + "']").click ();
<?php } ?>
</script>


