<link href="/blab/public/css/newsFeed.css" rel="stylesheet" type="text/css">
<link href="/blab/public/css/chat.css" rel="stylesheet" type="text/css">



<div class="row">
    <div class="col-md-6 pull-left userChatList">
        <div class="ibox" style="float:left; width: 100%">
            <div class="ibox-content" style="padding: 10px; float: left; width: 100%;">
                <h2>Chat</h2>

                <div class="input-group" style="width:100%;">
                    <input type="text" placeholder="Search Users " id="chatUserSearchBox" class="input form-control pull-left">
                    <input style="display:none;" type="text" placeholder="Search Pages" id="chatPageSearchBox" class="input form-control pull-left">

                </div>

                <ul class="category-list" style="padding: 0; width: 100%;">

                    <?php $this->partial ("chat/searchChatUsers", ["arrPages" => $arrPages, "arrPageCategories" => $arrPageCategories, "arrChatGroups" => $arrChatGroups, "arrMessages" => $arrMessages, "arrGroups" => $arrGroups]); ?>

                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-12 discoverWindow pull-left">

    </div>

    <div class="col-md-12 chatWindow pull-left">

    </div>
</div>



<script src="/blab/public/js/geocomplete.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA1COtE7cJxfGxNWiTjEgtSNhbvDBCiiqQ&libraries=places"></script>
<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/chat.js" type="text/javascript"></script>

<script>
<?php
if ( !empty ($_GET['username']) )
{
    ?>
        var username = '<?= $_GET['username'];  ?>';
                $ (".single[username='" + username + "']").click ();
<?php } ?>
</script>


