<link href="/blab/public/css/newsFeed.css" rel="stylesheet" type="text/css">
<link href="/blab/public/css/chat.css" rel="stylesheet" type="text/css">


<?php

/**
 * build html ordered by page category
 * @return string
 */
function getPageHtml ($arrPages, $rootPath)
{
    if ( !empty ($arrPages) )
    {

        $arrPageData = [];

        foreach ($arrPages as $key => $objPage) {

            if ( !isset ($arrPageData[$objPage->getCategories ()]) )
            {
                $arrPageData[$objPage->getCategories ()][$key] = array();
            }


            if ( file_exists ($rootPath . $objPage->getFileLocation ()) )
            {
                $image = '<img style="width:25px; margin-right: 8px; float:left;" title="' . $objPage->getName () . '" alt="image" class="img-circle img-responsive" src="' . $objPage->getFileLocation () . '">';
            }
            else
            {
                $image = '<img style="width:25px; margin-right: 8px; float:left;" alt="image" class="img-circle img-responsive" src="/blab/public/img/avatar.gif">';
            }

            $html = '<li>
                                    <a class="show-chat page" groupname="' . $objPage->getName () . '" groupid="' . $objPage->getUrl () . '" href="#"> 
                                        ' . $image . '
                                        <i class="fa fa-circle text-danger"></i> ' . $objPage->getName () . ' 
                                    </a>
                                </li>';

            $arrPageData[$objPage->getCategories ()][$key] = $html;
        }
    }

    return $arrPageData;
}
?>

<div class="row">
    <div class="col-md-6 pull-left userChatList">
        <div class="ibox" style="float:left; width: 100%">
            <div class="ibox-content" style="padding: 10px; float: left; width: 100%;">
                <h2>Chat</h2>

                <div class="input-group" style="width:100%;">
                    <input type="text" placeholder="Search Users " id="chatUserSearchBox" class="input form-control pull-left">

                </div>

                <ul class="category-list" style="padding: 0; width: 100%;">

                    <div class="col-lg-12" style="width:100%; font-size: 14px; margin-bottom: 12px;">
                        <a href="#" class="showActiveUsers btn btn-success">Active</a>
                        <a href="#" class="showGroups btn btn-warning">Groups</a>
                        <a href="#" class="showDiscover btn btn-danger">Discover</a>
                        <a href="#" class="showAllChat btn btn-primary">All</a>
                    </div>

                    <div class="usersDiv">
                        <?php
                        echo '<h5>Friends</h5>';

                        foreach ($arrMessages as $objMessage):

                            if ( trim ($objMessage->getRecipient ()) !== "" )
                            {
                                $from = (int) $objMessage->getRecipient () === (int) $_SESSION['user']['user_id'] ? $objMessage->getAuthor () : 'You';
                            }
                            else
                            {
                                $from = '';
                            }

                            $onlineLabel = 'text-danger';
                            $activeLabel = 'chat-not-active-user';

                            if ( trim ($objMessage->getLastLogin ()) !== "" )
                            {
                                $dbdate = strtotime ($objMessage->getLastLogin ());
                                if ( time () - $dbdate <= 15 * 60 )
                                {
                                    $onlineLabel = 'text-navy';
                                    $activeLabel = 'chat-active-user';
                                }
                                else
                                {
                                    $onlineLabel = 'text-danger';
                                    $activeLabel = 'chat-not-active-user';
                                }
                            }
                            else
                            {
                                $onlineLabel = 'text-danger';
                                $activeLabel = 'chat-not-active-user';
                            }


                            if ( $objMessage->getUsername () !== $_SESSION['user']['username'] ):

                                if ( file_exists ($rootPath . '/blab/public/uploads/profile/' . $objMessage->getUsername () . '.jpg') )
                                {
                                    $image = '<img style="width:25px; margin-right: 8px; float:left;" title="' . $objMessage->getAuthor () . '" alt="image" class="img-circle img-responsive" src="/blab/public/uploads/profile/' . $objMessage->getUsername () . '.jpg">';
                                }
                                else
                                {
                                    $image = '<img style="width:25px; margin-right: 8px; float:left;" alt="image" class="img-circle img-responsive" src="/blab/public/img/avatar.gif">';
                                }
                                ?>
                                <li style="width:100%; border-bottom: 1px dotted #CCC; min-height: 32px; float: left;">
                                    <a class="show-chat single <?= $activeLabel ?>" groupname="" groupid="" username="<?= $objMessage->getUsername () ?>" fullname="<?= str_replace (" ", "|", $objMessage->getAuthor ()) ?>" session-user="<?= $_SESSION['user']['username'] ?>" user-id="<?= $objMessage->getUserId () ?>" href="#"> 

                                        <div class="col-lg-9">
                                            <?= $image ?>

                                            <?= $objMessage->getAuthor () ?> <br>
                                            <?= $from . ' ' . substr ($objMessage->getMessage (), 0, 20) ?>
                                        </div>

                                        <div class="col-lg-3">
                                            <?= date ("d F", strtotime ($objMessage->getDate ())) ?>
                                            <i class="fa fa-circle <?= $onlineLabel ?>"></i> 
                                        </div>
                                    </a>
                                </li>

                                <?php
                            endif;
                        endforeach;

                        echo '</div>';

                        echo '<div class="groupsDiv" style="width:100%;">';

                        if ( isset ($arrChatGroups) && !empty ($arrChatGroups) ):

                            echo '<h5>Groups</h5>';

                            foreach ($arrChatGroups as $arrChatGroup):
                                ?>
                                <li>
                                    <a class="show-chat group" groupname="<?= $arrChatGroup['name'] ?>" groupid="<?= $arrChatGroup['group_id'] ?>" username="<?= $arrChatGroup['users'] ?>" fullname="<?= $arrChatGroup['fullname'] ?>" session-user="<?= $_SESSION['user']['username'] ?>" href="#"> 
                                        <i class="fa fa-circle text-danger"></i> <?= $arrChatGroup['name'] ?> </a></li>

                                <?php
                            endforeach;
                        endif;

                        echo '</div>';

                        echo '<div class="discover" style="width:100%; display:none;">';

                        echo '<div style="width:100%; border-bottom: 1px dotted #CCC">';

                        echo '<h2>Pages</h2>';

                        $arrPageData = getPageHtml ($arrPages, $rootPath);

                        // pages here
                        if ( !empty ($arrPageData) )
                        {
                            foreach ($arrPageData as $categoryId => $pageCategory) {
                                echo '<h3>' . $arrPageCategories[$categoryId]->getName () . '</h3>';

                                foreach ($pageCategory as $pageHtml) {
                                    echo $pageHtml;
                                }
                            }
                        }

                        echo '</div>';



                        echo '<div class="full-height-scroll" style="overflow: hidden; width: auto; height: 100%;">

                                        <h2>Page Categories</h2>

                                        <ul class="list-group clear-list">';

                        foreach ($arrPageCategories as $arrPageCategory) {

                            echo '<li class="list-group-item fist-item filterPageCategory" style="border-bottom:1px dotted #CCC;" id="' . $arrPageCategory->getId () . '">
                                               ' . $arrPageCategory->getName () . '
                                            </li>';
                        }
                        echo '</ul>

                            </div>';

                        echo '</div>';
                        ?>

                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-12 discoverWindow pull-left">

    </div>

    <div class="col-md-12 chatWindow pull-left">

    </div>
</div>



<script src="/blab/public/js/geocomplete.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyA1COtE7cJxfGxNWiTjEgtSNhbvDBCiiqQ&libraries=places"></script>
<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/chat.js" type="text/javascript"></script>

<script>
<?php
if ( !empty ($_GET['username']) )
{
    ?>
        var username = '<? = $_GET['username'];
                ? > ';
                $ (".single[username='" + username + "']").click ();
<?php } ?>
</script>


