<?php

function getOnlineStatusLabel (Message $objUser)
{
    $onlineLabel = 'text-danger';

    if ( trim ($objUser->getLastLogin ()) !== "" )
    {
        $dbdate = strtotime ($objUser->getLastLogin ());
        if ( time () - $dbdate <= 15 * 60 )
        {
            $onlineLabel = 'text-navy';
        }
        else
        {
            $onlineLabel = 'text-danger';
        }
    }
    else
    {
        $onlineLabel = 'text-danger';
    }

    return $onlineLabel;
}

echo '<div class="col-lg-12" style="width:100%; font-size: 14px; margin-bottom: 12px;">
                        <a href="#" class="showActiveUsers btn btn-success">Active</a>
                        <a href="#" class="showGroups btn btn-warning">Groups</a>
                         <a href="#" class="showAllChat btn btn-primary">All</a>
                    </div>';
echo '<h5>Friends</h5>';

 foreach ($arrUsers as $objMessage):
                        
                        if(  trim ($objMessage->getRecipient()) !== "") {
                             $from = (int) $objMessage->getRecipient() === (int) $_SESSION['user']['user_id'] ? $objMessage->getAuthor() : 'You';
                        } else {
                            $from = '';
                        }

                        $onlineLabel = getOnlineStatusLabel ($objMessage);

    $activeLabel = trim ($onlineLabel) === 'text-navy' ? 'chat-active-user' : 'chat-not-active-user';

                        if ( $objMessage->getUsername () !== $_SESSION['user']['username'] ):
                            
                            if ( file_exists ($rootPath . '/blab/public/uploads/profile/' . $objMessage->getUsername () . '.jpg') )
                        {
                            $image = '<img style="width:25px; margin-right: 8px; float:left;" title="' . $objMessage->getAuthor () . '" alt="image" class="img-circle img-responsive" src="/blab/public/uploads/profile/' . $objMessage->getUsername () . '.jpg">';
                        }
                        else
                        {
                            $image = '<img style="width:25px; margin-right: 8px; float:left;" alt="image" class="img-circle img-responsive" src="/blab/public/img/avatar.gif">';
                        }
                            
                            ?>
                            <li style="width:100%; border-bottom: 1px dotted #CCC; min-height: 32px; float: left;">
                                <a class="show-chat single <?= $activeLabel ?>" groupname="" groupid="" username="<?= $objMessage->getUsername () ?>" fullname="<?= str_replace (" ", "|", $objMessage->getAuthor ()) ?>" session-user="<?= $_SESSION['user']['username'] ?>" user-id="<?= $objMessage->getUserId () ?>" href="#"> 
                                   
                                    <div class="col-lg-9">
                                        <?= $image ?>
                                   
                                        <?= $objMessage->getAuthor () ?> <br>
                                        <?= $from . ' ' . substr($objMessage->getMessage(), 0, 20) ?>
                                    </div>
                                    
                                    <div class="col-lg-3">
                                        <?= date("d F", strtotime($objMessage->getDate()))  ?>
                                         <i class="fa fa-circle <?= $onlineLabel ?>"></i> 
                                    </div>
                                </a>
                            </li>

                            <?php
                        endif;
                    endforeach;

 foreach ($arrAllUsers as $objMessages):
                        
                        if(  trim ($objMessages->getRecipient()) !== "") {
                             $from = (int) $objMessages->getRecipient() === (int) $_SESSION['user']['user_id'] ? $objMessages->getAuthor() : 'You';
                        } else {
                            $from = '';
                        }

                       $onlineLabel = getOnlineStatusLabel ($objMessages);

    $activeLabel = trim ($onlineLabel) === 'text-navy' ? 'chat-active-user' : 'chat-not-active-user';

                        if ( $objMessages->getUsername () !== $_SESSION['user']['username'] ):
                            
                            if ( file_exists ($rootPath . '/blab/public/uploads/profile/' . $objMessages->getUsername () . '.jpg') )
                        {
                            $image = '<img style="width:25px; margin-right: 8px; float:left;" title="' . $objMessages->getAuthor () . '" alt="image" class="img-circle img-responsive" src="/blab/public/uploads/profile/' . $objMessage->getUsername () . '.jpg">';
                        }
                        else
                        {
                            $image = '<img style="width:25px; margin-right: 8px; float:left;" alt="image" class="img-circle img-responsive" src="/blab/public/img/avatar.gif">';
                        }
                            
                            ?>
                            <li style="width:100%; min-height: 32px; float: left;">
                                <a style="display:none; border-bottom: 1px dotted #CCC;" class="show-chat single <?= $activeLabel ?>" groupname="" groupid="" username="<?= $objMessages->getUsername () ?>" fullname="<?= str_replace (" ", "|", $objMessages->getAuthor ()) ?>" session-user="<?= $_SESSION['user']['username'] ?>" user-id="<?= $objMessages->getUserId () ?>" href="#"> 
                                   
                                    <div class="col-lg-9">
                                        <?= $image ?>
                                   
                                        <?= $objMessages->getAuthor () ?> <br>
                                        <?= $from . ' ' . substr($objMessages->getMessage(), 0, 20) ?>
                                    </div>
                                    
                                    <div class="col-lg-3">
                                        <?= date("d F", strtotime($objMessages->getDate()))  ?>
                                         <i class="fa fa-circle <?= $onlineLabel ?>"></i> 
                                    </div>
                                </a>
                            </li>

                            <?php
                        endif;
                    endforeach;

if ( isset ($arrChatGroups) && !empty ($arrChatGroups) ):

    echo '<h5>Groups</h5>';

    foreach ($arrChatGroups as $arrChatGroup):
        ?>
        <li><a class="show-chat group" groupname="<?= $arrChatGroup['name'] ?>" groupid="<?= $arrChatGroup['group_id'] ?>" username="<?= $arrChatGroup['users'] ?>" fullname="<?= $arrChatGroup['fullname'] ?>" session-user="<?= $_SESSION['user']['username'] ?>" href="#"> <i class="fa fa-circle text-danger"></i> <?= $arrChatGroup['name'] ?> </a></li>

        <?php
    endforeach;
endif;
?>