<style>
    .chat-message {
        width:90% !important;
        clear:both;
    }

    .right {
        float: right !important;
    }

    .left {
        float: left !important;
    }
</style>


<?php
if ( !empty ($objPage) )
{
    echo '<input type="hidden" id="messagePageId" value="' . $objPage->getUrl () . '">';
}
elseif ( !empty ($objUser) )
{
    echo '<input type="hidden" id="messageUserId" value="' . $objUser->getId () . '">';
}


foreach ($arrMessages as $arrMessage):

    $name = $arrMessage->getAuthor ();

    if ( !empty ($objPage) )
    {
        if ( (int) $objPage->getUserId () === (int) $arrMessage->getSender () )
        {

            $image = file_exists ($rootPath . $objPage->getFileLocation ()) ? $objPage->getFileLocation () : 'blab/public/img/avatar.gif';
            $name = $objPage->getName ();
        }
    }
    else
    {
        if ( $arrMessage->getType () == "page" )
        {
            continue;
        }

        $image = file_exists ($rootPath . '/blab/public/uploads/profile/' . $arrMessage->getUsername () . '.jpg') ? '/blab/public/uploads/profile/' . $arrMessage->getUsername () . '.jpg' : 'blab/public/img/avatar.gif';
    }

    $width = 300;
    $height = 300;
    $embed = '';

    if ( $arrMessage->getType () == "img" )
    {
        continue;
    }

    $comment = $arrMessage->getMessage ();

    if ( preg_match ('/https:\/\/(?:www.)?(youtube).com\/watch\\?v=(.*?)/', $comment) )
    {
        $embed = preg_replace ("/\s*[a-zA-Z\/\/:\.]*youtube.com\/watch\?v=([a-zA-Z0-9\-_]+)([a-zA-Z0-9\/\*\-\_\?\&\;\%\=\.]*)/i", "<iframe class=\"embed-responsive-item\" width=\"" . $width . "\" height=\"" . $height . "\" src=\"//www.youtube.com/embed/$1\" frameborder=\"0\" allowfullscreen></iframe>", $comment);
    }

    if ( preg_match ('/https:\/\/vimeo.com\/(\\d+)/', $comment, $regs) )
    {
        $embed = '<iframe class="embed-responsive-item" src="http://player.vimeo.com/video/' . $regs[1] . '?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;color=ffffff" width="' . $width . '" height="' . $height . '" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>';
    }

    if ( $embed != "" )
    {
        $comment = '<div class="vasplus_a">
			<div class="vasplus_b">
			<div class="vasplus_c">
			<div class="vpb_video_link_a">
			<div class="vpb_data_size">
				  ' . $embed . '
				</div>
			
			
			</div>
			</div>
			</div></div>';
    }

    if ( $arrMessage->getSender () == $_SESSION['user']['user_id'] )
    {
        ?>

        <div class="chat-message chat-message-reply right chatWrappera">


            <div style="width:10%; float:right">
                <a href="#" class="deleteChatMessage pull-right" deleteid="<?= $arrMessage->getId () ?>"><i class="fa fa-trash"></i></a>
                <a href="#" class="forwardChatMessage pull-right" messageid="<?= $arrMessage->getId () ?>"><i class="fa fa-mail-forward"></i></a>
                <img class="message-avatar pull-right" src="<?= $image ?>" alt="">
            </div>

            <div style="width:90%; float: right">
                <div class="message" style="text-align:right">
                    <a class="message-author" href="#">  <?= $name ?> </a>
                    <span class="message-date"> <?= date ('F j, Y, g:i a', strtotime ($arrMessage->getDate ())); ?> </span>
                    <span class="message-content">

                        <?php
                        if ( $arrMessage->getType () == "img" )
                        {
                            echo '<a class="v_photo_holder" onclick="vpb_popup_photo_box(\'' . $arrMessage->getId () . '\', \'1\', 1, \'/blab/public/uploads/chat/' . $arrMessage->getFilename () . '\');">';
                            echo '<img style="width:110px; clear:both;" src="/blab/public/uploads/chat/' . $arrMessage->getFilename () . '">';
                            echo '</a>';
                        }
                        elseif ( $arrMessage->getType () == "audio" )
                        {
                            echo '<audio style="width:100%; float:left;" controls="controls" src="/blab/public/uploads/chat/' . $arrMessage->getFilename () . '"></audio>';
                        }
                        elseif ( $arrMessage->getType () == "file" )
                        {
                            echo '<a href="/blab/public/uploads/chat/' . $arrMessage->getFilename () . '" download>' . $arrMessage->getFilename () . '</a>';
                        }
                        ?>

                        <?= $comment ?>
                    </span>
                </div>
            </div>






        </div>


        <?php
    }
    else
    {
        ?>

        <div class="chat-message left chatWrappera">

            <div style="width:10%; float: left;">
                <a href="#" class="deleteChatMessage pull-right" deleteid="<?= $arrMessage->getId () ?>"><i class="fa fa-trash"></i></a>
                <a href="#" class="forwardChatMessage pull-right" messageid="<?= $arrMessage->getId () ?>"><i class="fa fa-mail-forward"></i></a>
                <img class="message-avatar" src="<?= $image ?>" alt="">
            </div>

            <div style="width:90%; float: left">
                <div class="message" style="text-align:left;">
                    <a class="message-author" href="#"> <?= $name ?> </a>
                    <span class="message-date"> <?= date ('F j, Y, g:i a', strtotime ($arrMessage->getDate ())); ?>  </span>
                    <span class="message-content">

                        <?php
                        if ( $arrMessage->getType () == "img" )
                        {
                            echo '<a class="v_photo_holder" onclick="vpb_popup_photo_box(\'' . $arrMessage->getId () . '\', \'1\', 1, \'/blab/public/uploads/chat/' . $arrMessage->getFilename () . '\');">';
                            echo '<img style="width:110px; clear:both;" src="/blab/public/uploads/chat/' . $arrMessage->getFilename () . '">';
                            echo '</a>';
                        }
                        elseif ( $arrMessage->getType () == "file" )
                        {
                            echo '<a href="/blab/public/uploads/chat/' . $arrMessage->getFilename () . '" download>' . $arrMessage->getFilename () . '</a>';
                        }
                        elseif ( $arrMessage->getType () == "audio" )
                        {
                            echo '<audio controls="controls" src="/blab/public/uploads/chat/' . $arrMessage->getFilename () . '"></audio>';
                        }
                        ?>

                        <?= $comment ?>
                    </span>
                </div>
            </div>
        </div>

        <?php
    }
    ?>



<?php endforeach; ?>