<div class="sbtn sbtn-success" style="margin:0px; margin-right:20px; margin-top:3px; line-height:normal; padding:5px; padding-left:10px; padding-right:10px; padding-bottom:7px; cursor:pointer; font-family:arial; font-size:14px !important; text-transform:none; margin-bottom:10px; float:right;" data-backdrop="static" data-toggle="modal" data-target="#add-session"><i class="fa fa-plus-square"></i> Add New Category</div><br clear="all">


<div style="width:98%; border:0px solid;margin:0 auto;" align="center"><br clear="all">
    <div style="width:20%; float:left;" align="left"><div id="vpb_loading_users_in_the_system"></div></div>
    <div style="width:80%; float:right;" align="right"></div>
    <div style="clear:both;"></div>
</div>
<br clear="all">

<table>
    <thead>
        <tr>
            <th class="tablenum">#</th>
            <th>Category Name</th>
            <th class="table_others">Actions</th>
        </tr>
    </thead>
    <tbody>
        
        <?php foreach ($arrCategories as $arrCategory): ?>
        
        <tr id="category_wrapper_<?= $arrCategory->getId() ?>">
            <td class="tablenum" vasplus-table-label="#"><?= $arrCategory->getId() ?></td>
            <td vasplus-table-label="Category Name" style="width:60%;">
                <span id="category_text_<?= $arrCategory->getId() ?>"><?= $arrCategory->getName() ?></span>
                <span id="category_box_<?= $arrCategory->getId() ?>" style="display:none;">
                    <div style="display:block;">
                        <input type="text" class="forms-controled" style=" min-width:200px;max-width:60%; float:left;border-radius:0px;" id="category_name<?= $arrCategory->getId() ?>" value="<?= $arrCategory->getName() ?>" autocomplete="off" placeholder="Type the name of the category here...">
                        <span class="sbtn-success" style="cursor:pointer; border-radius:0px; float:left;" onclick="vpb_add_category ('<?= $arrCategory->getId() ?>');">Save</span><div style="clear:both;"></div>
                    </div>

                </span>
            </td>
            <td class="table_others" vasplus-table-label="Actions">

                <span id="edit_<?= $arrCategory->getId() ?>" class="cbtn" style="margin:0px 12px; padding:3px 10px;" onclick="$ ('#category_text_<?= $arrCategory->getId() ?>').hide ();$ ('#category_box_<?= $arrCategory->getId() ?>').fadeIn ();$ ('#edit_<?= $arrCategory->getId() ?>').hide ();$ ('#cancel_<?= $arrCategory->getId() ?>').fadeIn ();"><i class="fa fa-pencil fa-fw"></i> Edit</span>

                <span id="cancel_<?= $arrCategory->getId() ?>" class="cbtn" style="display:none;margin:0px 12px; padding:3px 10px;" onclick="$ ('#category_box_<?= $arrCategory->getId() ?>').hide ();$ ('#category_text_<?= $arrCategory->getId() ?>').fadeIn ();$ ('#cancel_<?= $arrCategory->getId() ?>').hide ();$ ('#edit_<?= $arrCategory->getId() ?>').fadeIn ();"><i class="fa fa-times"></i> Cancel edit</span>

                <span class="cbtn" style="margin:0px 12px; padding:3px 10px;" data-backdrop="static" data-toggle="modal" data-target="#delete-category" onclick="$ ('#category_to_delete').html ('<?= $arrCategory->getName() ?>');$ ('#vasplus_data_id').val ('<?= $arrCategory->getId() ?>');"><i class="fa fa-trash-o fa-fw"></i> Delete</span>
            </td>
        </tr>
        <?php endforeach; ?>
        
        
       
    </tbody>
</table>
