<?php

echo '<div class="full-height-scroll" style="overflow: auto; width: auto; height: 400px; margin-top: 20px;
    float: left;
    width: 100%;
}">';

echo '<div class="col-lg-12 pull-left" style="margin-bottom:16px;">';
echo '<button id="createGroup" type="button" class="btn btn-w-m btn-primary">Create Group</button>';
echo '</div>';

if ( !empty ($arrGroups) )
{

    echo '<div class="col-lg-12">';
    echo '<ul class="list-group clear-list" style="padding:10px;">';

    foreach ($arrGroups as $arrGroup) {
        echo '<li class="list-group-item fist-item" style="border-bottom: 1px dotted #CCC;">';


        echo $arrGroup->getGroupName ();
        echo '<br/><small>' . $arrGroup->getDescription () . '<small>';


        echo '</li>';
    }

    echo '</div>';
    echo '</ul>';
    echo '</div>';
}
