<?php
$totalCommentsToDisplay = 1;

$friendIds = [];

foreach ($arrFriendList as $friend) {
    $friendIds[] = $friend->getId ();
}

$requestIds = [];

foreach ($arrFriendRequests as $objFriendRequest) {
    $requestIds[] = $objFriendRequest->getId ();
}
?>

<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <div class="row">
                <?php
                $this->partial ("templates/profileUpload", ["arrUser" => $objUser, "friendIds" => $friendIds, "requestIds" => $requestIds]);
                $this->partial ("templates/links");
                ?>
            </div>

        </div>

        <div class="col-md-9">
            <!-- Display Group Details -->

            <div class="vprofile_o_detail" style="border-bottom:0px solid !important;">
                <div class="vprofile_o_title" style="padding:0px;">
                    <div style="float:left; padding:10px;">
                        Groups            
                    </div>
                    <div style="float:right; padding:10px;">
                        <span class="create_btn" onclick="vpb_reset_current_group_details ();"><i class="fa fa-plus" style="font-weight:normal !important;"></i> Create Group</span>

                    </div><div style="clear:both;"></div></div>
                <div style="clear:both;"></div>
            </div>

            <div style="clear:both;"></div>

            <div style="margin:0 auto; text-align:center; display:table; width: 100%;" align="center">
                <input type="hidden" id="vtotal_groups" value="<?= $totalCount ?>">
                <input type="hidden" id="vpb_groups_start" value="<?= $paginationLimit ?>">
                <input type="hidden" id="vpb_total_groups_per_load" value="<?= $paginationLimit ?>">


                <div class="row">
                    <div class="col-lg-12">
                        <div class="wrapper wrapper-content animated fadeInUp">

                            <div class="ibox">
                                <div class="ibox-title">
                                    <h5>Groups you are a member of</h5>

                                </div>
                                <div class="ibox-content col-lg-12 pull-left">
                                    <?php
                                    foreach ($arrMemberGroups as $arrMemberGroup) {
                                        $image = trim ($arrMemberGroup->getImageLocation ()) !== "" && file_exists ($rootPath . $arrMemberGroup->getImageLocation ()) ? $arrMemberGroup->getImageLocation () : '/blab/public/img/avatar.gif';
                                        ?>

                                        <div class="vpb_groups_box member">
                                            <div class="col-lg-2 pull-left" style="padding:10px;">
                                                <a href="/blab/group/index/<?= $arrMemberGroup->getId () ?>">
                                                    <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                                <div class="vproducttitle">
                                                    <a href="/blab/group/index/<?= $arrMemberGroup->getId () ?>">
                                                        <span><?= $arrMemberGroup->getGroupName () ?></span>
                                                    </a>
                                                </div>
                                                <div class="vproductprice">
                                                    <div class="vpull_left">3 members</div>

                                                    <div style="clear:both;"></div>
                                                </div>
                                            </div>
                                        </div>

                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="input-group vpb-the-friends-wrap" id="vpb_load_more_group_box" style="margin-top: 12px;">
                    <div style="float:left;"><span class="vpb_hover" style="color:#3b5998;" onclick="vpb_load_more_groups ();">View more groups</span></div>
                    <div style="float:right; color:#999;"><span id="v_this_members_totals"><?= count ($arrGroups) ?></span> of <?= $totalCount ?></div>
                    <div style="clear:both;"></div>
                </div>

                <!-- Loading Gif -->
                <div class="input-group vpb-the-friends-wrap" style="display:none;padding:7px 10px !important;" id="vpb_loading_group_members_outer">
                    <div id="vpb_loading_group_members"></div>
                </div>


                <div class="col-md-12" style="padding:0px !important;">
                    <div class="input-group">
                        <input onkeyup="vpb_load_more_groups (true)" type="text" id="searchText" placeholder="Search" class="input-sm form-control"> 
                        <span class="input-group-btn">
                            <button onclick="vpb_load_more_groups (true)" type="button" class="btn btn-sm btn-primary"> Go!</button> 
                        </span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <div class="wrapper wrapper-content animated fadeInUp">

                            <div class="ibox">
                                <div class="ibox-title">
                                    <h5>Groups you are not a member of</h5>

                                </div>
                                <div class="ibox-content col-lg-12 pull-left">
                                    <div id="vpb_loaded_group_members" style=" width:100%;">
                                        <?php
                                        foreach ($arrGroups as $arrGroup) {

                                            $blHasRequest = false;

                                            $arrRequests = $arrGroup->getArrRequests ();

                                            if ( !empty ($arrRequests) )
                                            {
                                                foreach ($arrRequests as $objRequest) {
                                                    $arrUser = $objRequest->getArrUser ();

                                                    if ( is_object ($arrUser) && (int) $arrUser->getId () === (int) $objUser->getId () )
                                                    {
                                                        $blHasRequest = true;
                                                    }
                                                }
                                            }

                                            $displayCancel = $blHasRequest === true ? 'block' : 'none';
                                            $showRequest = $blHasRequest === false ? 'block' : 'none';
                                            $image = trim ($arrGroup->getImageLocation ()) !== "" && file_exists ($rootPath . $arrGroup->getImageLocation ()) ? $arrGroup->getImageLocation () : '/blab/public/img/avatar.gif';
                                            ?>

                                            <div class="vpb_groups_box notMember">
                                                <div class="col-lg-2 pull-left" style="padding:10px;">
                                                    <a href="/blab/group/index/<?= $arrGroup->getId () ?>">
                                                        <img src="<?= $image ?>" class="img-responsive" border="0"></a>
                                                    <div class="vproducttitle">
                                                        <a href="/blab/group/index/<?= $arrGroup->getId () ?>">
                                                            <span><?= $arrGroup->getGroupName () ?></span>
                                                        </a>
                                                    </div>
                                                    <div class="vproductprice">
                                                        <div class="vpull_left"><?= $arrGroup->getMemberCount () ?> members</div>
                                                        <div class="vpull_right">

                                                            <span id="group_join_<?= $arrGroup->getId () ?>" onclick="vpb_send_request_to_join_group (<?= $arrGroup->getId () ?>, 'Jelzon11', 'michaelhampton', 'join');" class="cbtn" style="font-family:arial !important; font-size:13px !important;padding:3px 10px !important;margin:0px !important; display: <?= $showRequest ?>"><i class="fa fa-plus"></i> Join</span>

                                                            <span id="group_requestsent_<?= $arrGroup->getId () ?>" style="display:<?= $displayCancel ?>;">
                                                                <span class="cbtn" style="font-family:arial !important; font-size:13px !important;padding:3px 10px !important;margin:0px !important;opacity:0.6;cursor:default;"><i class="fa fa-reply"></i> Request Sent</span>

                                                                <span class="cbtn vpb_cbtn" style="font-family:arial !important; font-size:13px !important;padding:3px 10px !important;margin:0px !important;" title="Cancel Request" onclick="vpb_send_request_to_join_group (<?= $arrGroup->getId () ?>, 'Jelzon11', 'michaelhampton', 'cancel');"><i class="fa fa-times"></i></span>
                                                            </span></div>
                                                        <div style="clear:both;"></div>
                                                    </div>
                                                </div>
                                            </div>

<?php } ?>

                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>


        </div>
    </div>


</div>

<script src="/blab/public/js/newsFeed.js" type="text/javascript"></script>
<script src="/blab/public/js/geocomplete.js"></script>