<!DOCTYPE html>
<html>

    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>The Blab | Forgot Password</title>

        <link href="/blab/public/css/bootstrap.css" rel="stylesheet">
        <link href="/blab/public/font-awesome/css/font-awesome.css" rel="stylesheet">

        <link href="/blab/public/css/animate.css" rel="stylesheet">
        <link href="/blab/public/css/style.css" rel="stylesheet">
        <link href="/blab/public/css/sweetalert.css" rel="stylesheet">

    </head>

    <body class="gray-bg">

        <div class="passwordBox animated fadeInDown">
            <div class="row">

                <div class="col-md-12">
                    <div class="ibox-content">

                        <h2 class="font-bold">Forgot password</h2>

                        <p>
                            Enter your email address and your password will be reset and emailed to you.
                        </p>

                        <div class="row">

                            <div class="col-lg-12">
                                <form class="m-t" role="form" action="index.html" id="forgotPasswordForm">
                                    <div class="form-group">
                                        <input name="password" type="password" class="form-control" placeholder="Enter New Password" required="required">
                                    </div>
                                    
                                     <div class="form-group">
                                        <input name="confirmPassword" type="password" class="form-control" placeholder="Confirm Password" required="required">
                                    </div>
                                    
                                    <input type="hidden" name="token" value="<?= $token ?>">

                                    <button type="submit" class="btn btn-primary block full-width m-b">Save new password</button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <hr/>
            <div class="row">
                <div class="col-md-6">
                    Copyright Example Company
                </div>
                <div class="col-md-6 text-right">
                    <small>© 2014-2015</small>
                </div>
            </div>
        </div>

    </body>

</html>

<script src="/blab/public/js/jquery-2.1.1.js"></script>
<script src="/blab/public/js/inspinia.js"></script>
<script src="/blab/public/js/bootstrap.js"></script>
<script src="/blab/public/js/sweetalert.js"></script>

<script>
    $ ("#forgotPasswordForm").on ("submit", function ()
    {
        var formData = $ (this).serialize ();

        $.ajax ({
            url: '/blab/resetPassword/saveResetPassword',
            type: 'POST',
            data: formData,
            success: function (response)
            {
                var objResponse = $.parseJSON (response);

                if (objResponse.sucess == 0)
                {
                    showErrorMessage (objResponse.message);
                }
                else
                {
                    showSuccessMessage ('You have been emailed');
                }

                return false;
            }
        });

        return false;
    });

    function showSuccessMessage (message)
    {
        message = message || "The action was complete successfully.";

        swal ({
            title: "Success",
            text: message,
            type: "success",
            showCancelButton: false,
            confirmButtonColor: "#1ab394",
            confirmButtonText: "Ok",
            closeOnConfirm: false

        });
    }

    function showErrorMessage (message)
    {
        message = message || "Somethinh went wrong whilst trying to complete the request";

        swal ({
            title: "Error",
            text: message,
            type: "error",
            showCancelButton: false,
            confirmButtonColor: "#1ab394",
            confirmButtonText: "Ok",
            closeOnConfirm: false,
            html: true

        });
    }
</script>
