<script src="/blab/public/js/jquery.validate.min.js"></script>

<script>
    document.title = 'Post New Job';
    $ ('body').removeClass ('body-bg');
    $ ('body').addClass ('body-bc');
    $ ('header').removeClass ('shadow');

    $ (document).ready (function ()
    {
        $ ("#expires").datepicker ({
            dateFormat: 'yy-mm-dd',
            minDate: 0
        });
        $ ('#post_job').submit (function ()
        {
            $ ('#responsibilities').val ("<ul class='bullets'><li>" + $.trim ($ ('#responsibilities').val ()).split ('\n').join ('</li><li>') + "</li></ul>");
            $ ('#skills').val ("<ul class='bullets'><li>" + $.trim ($ ('#skills').val ()).split ('\n').join ('</li><li>') + "</li></ul>");
            $ ('#perks').val ("<ul class='bullets'><li>" + $.trim ($ ('#perks').val ()).split ('\n').join ('</li><li>') + "</li></ul>");
        });

        $ ('#post_job').validate ({
            rules: {
                title: {
                    required: true,
                    minlength: 4,
                    maxlength: 80,
                },
//                company: {
//                    required: true,
//                    minlength: 4,
//                    maxlength: 80,
//                },
                location: {
                    required: true,
                },
                description: {
                    required: true,
                },
                responsibilities: {
                    required: true,
                },
                skills: {
                    required: true,
                },
                perks: {
                    required: true,
                },
                salary_min: {
                    required: true,
                    lessThanEqual: '#salary_max',
                },
                salary_max: {
                    required: true,
                },
                duration: {
                    required: true,
                },
                expires: {
                    required: true,
                },
            },
            messages: {
                title: {
                    required: "Enter job title.",
                    minlength: "Title is too short.",
                    maxlength: "Title is too long.",
                },
//                company: {
//                    required: "Enter company name.",
//                    minlength: "Company name is too short.",
//                    maxlength: "Company name is too long.",
//                },
                location: {
                    required: "Select job location.",
                },
                description: {
                    required: "Enter job description.",
                },
                responsibilities: {
                    required: "Enter job responsibilities.",
                },
                skills: {
                    required: "Enter skills required.",
                },
                perks: {
                    required: "Enter perks & benefits.",
                },
                salary_min: {
                    required: "Enter salary.",
                    lessThanEqual: "Validate min-max range.",
                },
                salary_max: {
                    required: "Enter salary.",
                },
                duration: {
                    required: "Select job duration type.",
                },
                expires: {
                    required: "Select job expiry date.",
                },
            },
        });
        $ ('#post_job').submit (function ()
        {
            if (!$ ('#post_job').valid ())
            {
                return false;
            }

            if ($.trim ($ ("#form_type").val ()) === "edit")
            {
                var strUrl = '/blab/job/saveUpdate';
            }
            else
            {
                var strUrl = '/blab/job/saveJob';
            }

            var formData = $ ("#post_job").serialize ();

            $.post (strUrl, formData, function (response)
            {
                try {
                    var objResponse = $.parseJSON (response);

                    if (objResponse.sucess == 1)
                    {
                        alert ('The job has been created successfully');
                        return false;
                    }
                    else
                    {
                        $ ("#v-wall-message").html ('Something went wrong whilst trying to save the job');
                        $ ("#v-wall-alert-box").click ();
                        return false;
                    }
                } catch (error) {
                    $ ("#v-wall-message").html ('Something went wrong whilst trying to save the job');
                    $ ("#v-wall-alert-box").click ();
                    return false;
                }
            }).fail (function (xhr, ajaxOptions, theError)
            {
                $ ("#vpb_loading_status_updates").html (''); //Hide loading image
                $ ("#v-wall-message").html ($ ("#general_system_error").val ());
                $ ("#v-wall-alert-box").click ();
                vpb_running_process = false;
                //return false;
            });

            return false;
        });

        $ ('#submit_job').click (function ()
        {
            if (!$ ('#post_job').valid ())
            {
                return false;
            }
        });
        $ ('#salary_min,#salary_max').keyup (function ()
        {
            $ ('#salary_min').valid ();
        });
    });

</script>

<style>
    input, select, textarea {width: 100%;resize: none;}
    p {margin: 7px 0;}
    input[type=number]{-moz-appearance:textfield}input::-webkit-inner-spin-button,input::-webkit-outer-spin-button{-webkit-appearance:none}
    .message{color: #e06c17;font-size: 14px;background: aliceblue;padding: 11px 4px;}
    .error:not(input){color: #ea1d1d;font-size: 13px;float: left;}
    .error-p{color: #ea1d1d;font-size: 13px;margin: 7px;}
    .signin-a,.signup-a  {cursor:pointer;}
    .login-page {margin: auto;top: 70px;position: relative;}
    .form {position: relative;z-index: 1;background: #FFFFFF;padding: 7vh 5vw;text-align: center;box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);}
    .form input textarea{outline: none;float:left;border: 1px solid #ccc;margin: 15px 0 0;padding: 15px;box-sizing: border-box;font-size: 14px;}
    .form button {font-family: "Roboto", sans-serif;text-transform: uppercase;outline: 0;background: #4CAF50;width: 100%;border: 0;margin: 15px 0 0;padding: 15px;color: #FFFFFF;font-size: 14px;-webkit-transition: all 0.3 ease;transition: all 0.3 ease;cursor: pointer;}
    .form button:hover,.form button:active,.form button:focus {background: #43A047;}
    .login_action {margin: 15px 0 0;color: #b3b3b3;font-size: 12px;}
    .login_action a {color: #4CAF50;text-decoration: none;}

</style>
<section class="login-page">

    <div class="row">
        <div class='col-xs-12 col-sm-12 col-md-12 col-lg-12 row'>
            <div class="col-xs-0 col-sm-2 col-md-3 col-lg-3"></div>
            <div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">
                
                <a href="/blab/job/getJobs?pageId=<?= $pageId ?>">Back</a>
                
                <div class="form">
                    <p style=" text-align: center; color: #5182a7; font-size: 120%;" class="row"><?php
                        if ( $addType == 'edit' )
                        {
                            echo "Edit Job";
                        }
                        else
                        {
                            echo "Post New Job";
                        }
                        ?></p>
                    <form class="post_job" name="post_job" id="post_job" method='post' action='/blab/job/saveJob'>

                        <input type="hidden" id="pageId" name="pageId" value="<?= $pageId ?>">

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Job Title:</p>
                            <input type="text" name='title' id='title' class='form-control' placeholder="Job Title"  value="<?php
                            if ( $addType == 'edit' )
                            {
                                echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>"), array("", "", "", ""), $objJob->getTitle ()));
                                ?><?php }
                            ?>"/>
                        </div>

<!--                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Company Name:</p>
                            <input type="text" name='company' id='company' class='form-control' placeholder="Company Name"  value="<?php
                            if ( $addType == 'edit' )
                            {
                                echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>"), array("", "", "", ""), $objJob->getPageName ()));
                            }
                            ?>"/>
                        </div>-->

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Location:</p>
                            <input type="text" name='location' id='location' class='form-control' value = "<?php
                            if ( $addType == 'edit' )
                            {
                                echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>"), array("", "", "", ""), $objJob->getLocation ()));
                            }
                            ?>"/>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Job Description:</p>
                            <textarea rows='3' name='description' id='description' class='form-control' placeholder="add new description on new line" ><?php
                                if ( $addType == 'edit' )
                                {
                                    echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>", "\n"), array("", "", "", "", "\n"), $objJob->getDescription ()));
                                }
                                ?></textarea>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Responsibilities:</p>
                            <textarea rows='3' name='responsibilities' id='responsibilities' class='form-control' placeholder="add new responsibilities on new line"><?php
                                if ( $addType == 'edit' )
                                {
                                    echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>", "\n"), array("", "", "", "", "\n"), $objJob->getResponsibilities ()));
                                }
                                ?></textarea>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Skills Required:</p>
                            <textarea rows='3' name='skills' id='skills' class='form-control'  placeholder="add new skill on new line"><?php
                                if ( $addType == 'edit' )
                                {
                                    echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>", "\n"), array("", "", "", "", "\n"), $objJob->getSkills ()));
                                }
                                ?></textarea>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Perks & Benefits:</p>
                            <textarea rows='3' name='perks' id='perks' class='form-control'  placeholder="add new benefit on new line"><?php
                                if ( $addType == 'edit' )
                                {
                                    echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>", "\n"), array("", "", "", "", "\n"), $objJob->getPerks ()));
                                }
                                ?></textarea>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Annual Salary:</p>
                            <div class='col-sm-6' style='padding: 0;padding-right: 10px'><input type="number" name='salary_min' id='salary_min' class='form-control' placeholder="min" value="<?php
                                if ( $addType == 'edit' )
                                {
                                    echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>"), array("", "", "", ""), $objJob->getMinSalary ()));
                                }
                                ?>"/></div>
                            <div class='col-sm-6' style='padding: 0;padding-left: 10px'><input type="number" name='salary_max' id='salary_max' class='form-control' placeholder="max"  value="<?php
                                if ( $addType == 'edit' )
                                {
                                    echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>"), array("", "", "", ""), $objJob->getMaxSalary ()));
                                }
                                ?>"/></div>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Job Duration:</p>
                            <select  name='duration' id='duration' class='form-control' >
                                <option value='Full time' <?php
                                if ( $addType == 'edit' && trim ($objJob->getDuration ()) == 'Full time' )
                                {
                                    ?> selected<?php } ?>>Full time</option>
                                <option value='Part time'<?php
                                if ( $addType == 'edit' && trim ($objJob->getDuration ()) == 'Part time' )
                                {
                                    ?> selected<?php } ?>>Part time</option>
                            </select>
                        </div>

                        <div class="form-group row">
                            <p style='text-align:left;color: #e78217;font-size: 16px;'>Expiry Date</p>
                            <input type="text" name='expires' id='expires' class='datepicker form-control' placeholder="Expiry Date"  value="<?php
                            if ( $addType == 'edit' )
                            {
                                echo strip_tags (str_replace (array("<ul class='bullets'>", "</ul>", "<li>", "</li>"), array("", "", "", ""), $objJob->getExpires ()));
                            }
                            ?>"/> 
                        </div>

                        <?php
                        if ( $addType == 'edit' )
                        {
                            ?> 
                            <input type='hidden' id="form_type" name='form_type' value='edit'> 
                            <input type="hidden" name="job_id" value="<?= $objJob->getId () ?>">
                            <button id='register'>SAVE CHANGES</button>
                            <?php
                        }
                        else
                        {
                            ?> 
                            <input type='hidden' id="form_type" name='form_type' value='submit'> 
                            <button type='submit' id='submit_job'>SUBMIT</button>
                        <?php } ?>
                        <input type='hidden' name='form' value='1'>
                    </form>
                </div>

            </div>
            <div class="col-xs-0 col-sm-2 col-md-3 col-lg-3"></div>
        </div>
    </div>




</section>