<style>
    .back-to-top {cursor: pointer;position: fixed;bottom: 0;right: 20px;display:none;width: 40px;height: 40px;}
    .all-jobs{padding-top:70px;}
    .container{width: 100%;line-height: 1.5;}
    .filters{background:#FFF;margin: 10px 0;padding:10px 25px;float:right;}
    .results{background:#FFF;margin: 10px 0;float:right;padding:4vh 3vw;}
    .filter-title{text-align: left;padding:15px 0 1px 0;font-size: 100%;color: #5182a7;border-bottom: 1px solid #dadada;}
    .chevron{float: right;margin-top: 3px;font-size: 13px;font-weight: lighter;}
    label{margin: 0 5px;}
    .single-item{font-size: 100%;color: #6b6b6b;margin: 3px 0;}
    .item-group{max-height: 160px;overflow-y: auto;}
    .sliderange{border:0;color: #5182a7;font-size: 88%;font-weight: lighter;padding: 10px 0;}
    .single-fliter {margin: 5px 0;}
    .single-res{}
    .p0 {padding:0}
    .job-icon{margin: 8px 0;width: 50px;height: 50px;background: #5182ba;color: #fff;font-size: 180%;text-align: center;padding: 2px 3px;text-shadow: 1px 1px 1px #22446b;}
    .job-title{font-size: 120%;color: #5182ba;}	
    .job-company{color: #8c8a8a;font-size: 90%;}
    .job-location{color: #8c8a8a;font-size: 93%;line-height: 1.5;padding:0;display: inline-block;}
    .job-description {color: #616161;}
    .job-salary{color: #8c8a8a;font-size: 93%;line-height: 1.5;display: inline-block;}
    .job-duration{color: #8c8a8a;font-size: 93%;line-height: 1.5;display: inline-block;}
    .job-expires{color: #8c8a8a;font-size: 93%;padding:0;line-height: 1.5;display: inline-block;}
    .job-created_by{color: #5182a7;font-size: 93%;padding:0;line-height: 1.5;}
    .fa1{font-size: 80%;margin: 0 7px 0 0;color:#86898c;}
    .single-job{padding-top: 70px;}
    .pre-wrap{white-space: pre-wrap;margin-left:18px;}
    .job-section{background: #fff;margin-right: auto;margin-left: auto;padding: 7vh;}
    .bullets{list-style-type: disc;}
    .divider1{width: 100%;border-bottom: 1px solid #dedede;margin: 14px 0px;}
    #slider-range{margin: 0 45px 0 10px;}
</style>

<section class='all-jobs'>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
                    <div class="filters col-xs-12 col-sm-12 col-md-10 col-lg-11">
                        <form>
                            <div class='filter-title'>Refine Results</div>

                            <div class='single-fliter'>
                                <div class='filter-title'>Duration</div>
                                <div class='item-group'>
                                    <div class='single-item'>
                                        <select id="duration" name="duration">
                                            <option value="">Select Duration</option>
                                            <option value="Full time">Full Time</option>
                                            <option value="Part time">Part Time</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class='single-fliter'>
                                <div class='filter-title'>Location<i  id='clear_location' style='float: right;margin: 1px 2px;font-size: 80%;text-decoration: underline;cursor:pointer;'>Clear</i></div>
                                <div class='item-group'>

                                    <?php
                                    foreach ($arrLocations as $key => $arrLocation) {
                                        ?>
                                        <div class='single-item'>
                                            <input type='checkbox' name='city[]' class='location_check' id='city-<?= $key ?>' value='<?= $arrLocation['location'] ?>' <?php
                                    if ( isset ($_GET['city']) && in_array ($arrLocations, $_GET['city']) )
                                    {
                                            ?> checked <?php } ?>>
                                            <label for='city-<?= $key ?>'><?= $arrLocation['location'] ?></label>
                                        </div>

                                    <?php }
                                    ?>							 
                                </div>		
                            </div>		
                            <div class='single-fliter'>
                                <div class='filter-title'>Compensation<i class='chevron glyphicon glyphicon-chevron-down'></i></div>
                                <div class='item-group'>
                                    <div class='single-item'>			
                                        <div class='sliderange'></div>
                                        <input type="hidden" name='salary_min' id="salary_min" value='<?php
                                    if ( isset ($_GET['salary_min']) )
                                    {
                                        $salary_min = $_GET['salary_min'];
                                    } echo $salary_min;
                                    ?>' readonly>
                                        <input type="hidden" name='salary_max' id="salary_max" value='<?php
                                        if ( isset ($_GET['salary_max']) )
                                        {
                                            $salary_max = $_GET['salary_max'];
                                        } echo $salary_max;
                                    ?>' readonly>

                                        <div id="slider-range"></div>							 
                                    </div>
                                </div>					
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-8 col-md-7 col-lg-8">
                    <div class="results col-xs-12 col-sm-12 col-md-12 col-lg-12"></div>
                </div>
                <div class="col-xs-12 col-sm-0 col-md-1 col-lg-1"></div>
            </div>
        </div>
    </div>
</div>
</section>
<a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Back to Top" data-toggle="tooltip" data-placement="top">
    <span class="glyphicon glyphicon-chevron-up"></span>
</a>
<script>
    var ajax_call = '';
    /*display job results*/
    function get_result ()
    {
        var str = $ ("form").serialize ();
        // ajax_call = $.ajax({});
        // ajax_call.abort();
        //var url = '/blab/job/searchJobs?' + str;
        //history.pushState (str, 'Find jobs', url);
        ajax_call = $.ajax ({
            url: '/blab/job/searchJobs',
            method: 'post',
            data: str,
            success: function (response)
            {
                try {
                    var objResponse = $.parseJSON (response);

                    if (objResponse.sucess == 0)
                    {

                        showErrorMessage (objResponse.message);

                    }

                } catch (error) {
                    $ (".results").html (response);
                }
            }
            , error: function (request, status, error)
            {
                showErrorMessage ('Ajax request failed unexpectedly');
            }
        });
    }

    $ (document).ready (function ()
    {
        get_result ();
        /*salary slider*/
        $ (function ()
        {
            $ ("#slider-range").slider ({
                range: true,
                min: <?= $salary_min ?>,
                max: <?= $salary_max ?>,
                values: [<?= $salary_min ?>, <?= $salary_max ?>],
                stop: function (event, ui)
                {
                    $ ("#salary_min").val (ui.values[ 0 ]);
                    $ ("#salary_max").val (ui.values[ 1 ]);
                    $ (".sliderange").html ("<i class='fa fa-inr'></i> " + ui.values[ 0 ] + " - <i class='fa fa-inr'></i> " + ui.values[ 1 ]);
                    get_result ();
                }
            });
            $ ("#salary_min").val ($ ("#slider-range").slider ("values", 0));
            $ ("#salary_max").val ($ ("#slider-range").slider ("values", 1));
            $ (".sliderange").html ("<i class='fa fa-inr'></i> " + $ ("#slider-range").slider ("values", 0) + " - <i class='fa fa-inr'></i> " + $ ("#slider-range").slider ("values", 1));
        });
        $ ("input[type='checkbox'], input[type='radio']").on ("click", get_result);
        $ ("select").on ("change", get_result);

        $ ('#clear_location').click (function ()
        {
            $ ('.location_check').removeAttr ('checked');
            get_result ();
        });

        $ (window).scroll (function ()
        {
            if ($ (this).scrollTop () > 50)
            {
                $ ('#back-to-top').fadeIn ();
            }
            else
            {
                $ ('#back-to-top').fadeOut ();
            }
        });
        // scroll body to 0px on click
        $ ('#back-to-top').click (function ()
        {
            $ ('#back-to-top').tooltip ('hide');
            $ ('body,html').animate ({scrollTop: 0}, 1000);
            return false;
        });
    });
</script>