<?php

if ( !empty ($arrJobs) )
{
    foreach ($arrJobs as $objJob) {
        echo "<div class='row single-res'>" .
        "	<div class='p0 col-sm-12 col-md-12'>" .
        "		<div class='p0 col-sm-2 col-lg-1'>" .
        "			<div class='job-icon'>" . $objJob->getTitle () . "</div></div>" .
        "		<div class='col-sm-10 col-lg-11'>" .
        "			<div>" .
        "				<div class='job-title '><a href='/blab/job/view/" . $objJob->getId () . "'>" . $objJob->getTitle () . "</a></div>" .
        "				<div class='job-company'><i class='fa1 fa fa-briefcase'></i>" . $objJob->getPageName () . "</div>" .
        "				<div class='job-description'>" . $objJob->getDescription () . "</div>" .
        "				<div class='p0 col-sm-12 col-md-12'>" .
        "					<div class='p0 job-location col-xs-12 col-sm-6 col-md-3 col-lg-2'><i class='fa1 fa fa-map-marker fa-2'></i>&nbsp;" . $objJob->getLocation () . "</div>" .
        "					<div class='p0 job-salary col-xs-12 col-sm-6 col-md-4 col-lg-3'><i class='fa1 fa fa-inr'></i>" . $objJob->getMinSalary () . " - " . $objJob->getMaxSalary () . "</div>" .
        "					<div class='p0 job-expires col-xs-12 col-sm-6 col-md-3 col-lg-2'><i class='fa1 fa fa-clock-o'></i>" . $objJob->getDuration () . "</div>" .
        "					<div class='p0 job-duration col-xs-12 col-sm-6 col-md-4 col-lg-2'><i class='fa1 fa fa-hourglass-half '></i>" . $objJob->getExpires () . "</div>" .
        "				</div>" .
        "			</div>" .
        "		</div>" .
        "		</div>" .
        "</div>";
    }
}
else
{
    echo '<h2>No jobs could be found </h2>';
}