<script>
    //document.title = '<?= $title ?> - Job Board';
    $ ('body').removeClass ('body-bg');
    $ ('body').addClass ('body-bc');
    $ ('header').removeClass ('shadow');
    $ (document).ready (function ()
    {
        $ (".ApplyForJob").on ("click", function ()
        {
            $ ("#jobApplicationModal").modal ("show");
        });

        $ ("#saveApplication").on ("click", function ()
        {
            var applicationText = $ ("#applicationText").val ();

            if (!applicationText)
            {
                alert ("You must enter some text");
                return false;
            }

            var applicationId = $ ("#applicationId").val ();

            if (!applicationId)
            {
                alert ("Invalid application id");
                return false;
            }

            $.post ('/blab/job/saveApplication', {"applicationText": applicationText, "applicationId": applicationId}, function (response)
            {

                try {
                    var objResponse = $.parseJSON (response);

                    if (objResponse.sucess == 0)
                    {
                        $ ("#v-wall-message").html (objResponse.message);
                        $ ("#v-wall-alert-box").click ();
                        return false;
                    }
                    else
                    {
                        alert ("The application has been sent successfully");
                    }
                } catch (error) {
                    $ ("#v-wall-message").html ('The ajax request ended unexpectedly');
                    $ ("#v-wall-alert-box").click ();
                }
            });
        });

        /*Edit job*/
        $ ('.edit-job').click (function ()
        {
            window.location = '/blab/job/edit/' +<?= $objJob->getId () ?>;
        });

        /*Delete job on confirm*/
        $ ('.delete-job').click (function ()
        {
            swal ({
                title: "Are you sure?",
                text: "You will not be able to recover this job!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function ()
            {
                $.ajax ({
                    url: '/blab/job/delete',
                    type: 'post',
                    dataType: 'json',
                    data: {id: '<?= $objJob->getId () ?>'},
                    success: function (res)
                    {
                        swal ("Deleted!", "The job has been deleted.", "success");
                    }, error: function (request, status, error)
                    {
                        showErrorMessage ('Ajax request failed unexpectedly');
                    }
                });
            });
        });
    });
</script>

<style>
    .actions{cursor:pointer;padding: 5px;}
    .actions:hover{color: #5182ba;}
    .container{width: 100%;line-height: 1.5;}
    .fa1{font-size: 80%;margin: 0 7px 0 0;color:#86898c;}
    .new-point{font-size: 115%;color: #5182ba;margin: 10px 0;text-decoration: underline;}
    .pre-wrap{white-space: pre-wrap;margin-left:18px;}
    .single-job{padding-top: 70px;}
    .job-section{    background: #fff;margin-right: auto;margin-left: auto;padding: 7vh;}
    .bullets{list-style-type: disc;}
    .divider1{width: 100%;border-bottom: 1px solid #ccc;margin: 14px 0px;}
    .p0 {padding:0}
    .job-icon{margin: 8px 0;width: 50px;height: 50px;background: #5182ba;color: #fff;font-size: 200%;text-align: center;padding: 2px 3px;text-shadow: 1px 1px 1px #22446b;}
    .job-title{font-size: 130%;}
    .job-company{color: #8c8a8a;font-size: 93%;line-height: 1.5;}
    .job-location{color: #8c8a8a;font-size: 93%;line-height: 1.5;padding:0;display: inline-block;}
    .job-salary{color: #8c8a8a;font-size: 93%;line-height: 1.5;display: inline-block;}
    .job-duration{color: #8c8a8a;font-size: 93%;line-height: 1.5;display: inline-block;}
    .job-expires{color: #8c8a8a;font-size: 93%;padding:0;line-height: 1.5;display: inline-block;}
    .job-created_by{color: #5182a7;font-size: 93%;padding:0;line-height: 1.5;}
</style>

<section class='single-job'>	
    <div class='container'>
        <div class='row col-sm-12 col-md-12 col-lg-12'>

            <div class='  col-sm-1 col-md-1 col-lg-1'></div>
            <div class='job-section  col-sm-10 col-md-10 col-lg-10'>
                <?php
                if ( !empty ($objJob) )
                {
                    if ( trim ($objJob->getUserId ()) !== "" && isset ($_SESSION['user']['user_id']) )
                    {
                        if ( (int) $objJob->getUserId () === (int) $_SESSION['user']['user_id'] )
                        {
                            ?>		
                            <div style='margin: -5vh;float: right;position: relative;'>
                                <i class='fa1 fa fa-pencil actions edit-job' title='Edit this job'></i>
                                <i class='fa1 fa fa-trash actions delete-job'  title='Delete this job'></i>
                            </div>
                            <?php
                        }
                    }
                    ?>
                    <div class='row'>
                        <div class='p0 col-sm-12 col-md-12'>
                            <div class='p0 col-sm-2 col-lg-1'>
                                <div class='job-icon'><?php echo ucfirst ($objJob->getTitle ()); ?></div></div>
                            <div class='col-sm-10 col-lg-11'>
                                <div>
                                    <div class='job-title '><?= $objJob->getTitle () ?></div>
                                    <div class='job-company'><i class='fa1 fa fa-briefcase'></i><?= $objJob->getPageName () ?></div>
                                    <div class='p0 col-sm-12 col-md-12'>
                                        <div class='p0 job-location col-sm-5 col-md-2 col-lg-2'><i class='fa1 fa fa-map-marker fa-2'></i>&nbsp;<?= $objJob->getLocation () ?></div>
                                        <div class='p0 job-salary col-sm-5 col-md-9 col-lg-10'><i class='fa1 fa fa-inr'></i><?= $objJob->getMinSalary () ?> - <?= $objJob->getMaxSalary () ?></div>

                                    </div>
                                    <div class='p0 col-sm-12 col-md-12'>
                                        <div class='p0 job-expires col-sm-5 col-md-2 col-lg-2'><i class='fa1 fa fa-clock-o'></i><?= $objJob->getDuration () ?></div>
                                        <div class='p0 job-duration col-sm-5 col-md-9 col-lg-10'><i class='fa1 fa fa-hourglass-half '></i><?= $objJob->getExpires () ?></div>
                                    </div>
                                    <div class='p0 job-created_by col-sm-12 col-md-12'><i class='fa1 fa fa-user'></i><?= $objJob->getPageName () ?></div>		
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class='divider1'></div>		

                    <div class='row'>
                        <div class='p0 col-sm-1 col-lg-1'></div>
                        <div class='col-sm-11 col-lg-11'>
                            <div class='new-point'>Job Description:</div>
                            <div class='job-description'><?= $objJob->getDescription () ?></div>
                            <div class='new-point'>Job Responsibilities:</div>
                            <div class='pre-wrap job-responsibilities'><?= $objJob->getResponsibilities () ?></div>
                            <div class='new-point'>Skills & Expertise :</div>
                            <div class='pre-wrap job-skills'><?= $objJob->getSkills () ?></div>
                            <div class='new-point'>Perks & Benefits:</div>
                            <div class='pre-wrap job-perks'><?= $objJob->getPerks () ?></div>
                        </div>
                    </div>

                    <button type="button" class="btn btn-primary btn-sm ApplyForJob">Apply</button>
                    <?php
                }
                else
                {
                    echo "<div style='text-align: center;font-size: 120%;color: #585755;'>No data found</div>";
                }
                ?>
            </div>
            <div class=' col-sm-1 col-md-1 col-lg-1'></div>
        </div>
    </div>
</section>

<div class="modal inmodal" id="jobApplicationModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content animated bounceInRight">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <i class="fa fa-laptop modal-icon"></i>
                <h4 class="modal-title">Apply for job</h4>
<!--                <small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small>-->
            </div>
            <div class="modal-body">
                <input type="hidden" id="applicationId" name="applicationId" value="<?= $objJob->getId () ?>">
<!--                <p><strong>Lorem Ipsum is simply dummy</strong> text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown
                    printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,
                    remaining essentially unchanged.</p>-->
                <div class="form-group">
                    <label>Why are you applying for this job?</label> 
                    <textarea id="applicationText" name="applicationText" placeholder="What can you bring to this job" class="form-control"></textarea></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" id="saveApplication" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

